"""GENERATED by rust/build.sh from rust/fylite/src/c_api.rs — do not edit.

The ABI version the built library speaks.  Generated rather than kept in
step by hand so the two cannot disagree.
"""
ABI_VERSION = 152
