"""GENERATED by rust/build.sh from rust/fylite/src/mapping.rs
-- do not edit.

The TGYRO boundary's CGS constants, with eV temperatures — the units
that port works in.  They are declared in the kernel beside the
formulas that use them; a host that spells one again is keeping a
physical constant in step by hand, and the failure mode is a
correction applied to one copy.

★These are the UPSTREAM values, not current CODATA: a more accurate
electron mass would make the port stop reproducing the code it is a
port of, by a few parts in ten thousand on every collision-derived
quantity — small enough to read as a convergence difference.
"""

#: erg/eV
K = 1.6022e-12

#: statcoulomb
E = 4.8032e-10

#: electron mass, g
ME = 9.1094e-28

#: deuterium mass, g — the normalising mass
MD = 3.34358e-24

#: proton mass, g
MP = 1.6726e-24

#: cm/s
C_LIGHT = 2.9979e10
