"""GENERATED by rust/build.sh from rust/fylite/src/mapping.rs, rust/fylite/src/gyrofluid.rs, rust/fylite/src/zerod.rs, rust/fylite/src/heating.rs, rust/fylite/src/sources.rs
-- do not edit.

Name orders the kernel publishes, declared beside the code that uses
them.  Two kinds, and both are POSITIONAL contracts: the upstream
deck names a port speaks (NEO, TGLF), and the vocabularies whose
INDEX is the wire format for a selector argument.  A host that
spells either one again is keeping a contract in step by hand.
"""

LH_EFFICIENCY_MODEL_NAMES = (
    "fisch",
)

NEO_DECK_GEOMETRY = (
    "RMIN_OVER_A", "RMAJ_OVER_A", "ZMAG_OVER_A", "S_ZMAG", "Q", "SHEAR",
    "SHIFT", "KAPPA", "S_KAPPA", "DELTA", "S_DELTA", "ZETA", "S_ZETA"
)

NEO_DECK_SCALARS = (
    "NU_1", "IPCCW", "BTCCW", "OMEGA_ROT", "OMEGA_ROT_DERIV"
)

NEO_DECK_SPECIES = (
    "Z", "MASS", "DENS", "TEMP", "DLNNDR", "DLNTDR"
)

NEO_SAUTER_SLOTS = (
    "RMIN_OVER_A", "RMAJ_OVER_A", "Q", "SHEAR", "SHIFT", "ZMAG_OVER_A",
    "S_ZMAG", "KAPPA", "S_KAPPA", "DELTA", "S_DELTA", "ZETA", "S_ZETA",
    "N_THETA"
)

PHASE_NAMES = (
    "breakdown", "rampup", "flattop", "rampdown"
)

TAU_LAW_NAMES = (
    "ipb98y2", "iter89p"
)

TGLF_DECK_GEOMETRY = (
    "RMIN_LOC", "RMAJ_LOC", "ZMAJ_LOC", "DRMAJDX_LOC", "DZMAJDX_LOC",
    "KAPPA_LOC", "S_KAPPA_LOC", "DELTA_LOC", "S_DELTA_LOC", "ZETA_LOC",
    "S_ZETA_LOC", "RMIN_SA", "RMAJ_SA", "Q_SA", "SHAT_SA"
)

TGLF_DECK_SPECIES = (
    "ZS", "MASS", "AS", "TAUS", "RLNS", "RLTS"
)

TGLF_DECK_SPECIES_KYGRID = (
    "ZS", "MASS", "AS", "TAUS"
)

TGLF_DECK_SPECIES_PRESSURE = (
    "AS", "TAUS", "RLNS", "RLTS"
)

TGLF_DECK_SPECIES_ROTATING = (
    "ZS", "MASS", "AS", "TAUS", "RLNS", "RLTS", "VPAR", "VPAR_SHEAR"
)

TGLF_MILLER_SLOTS = (
    "RMIN_LOC", "RMAJ_LOC", "ZMAJ_LOC", "Q_LOC", "KAPPA_LOC",
    "S_KAPPA_LOC", "DELTA_LOC", "S_DELTA_LOC", "ZETA_LOC", "S_ZETA_LOC",
    "DRMAJDX_LOC", "DZMAJDX_LOC", "DRMINDX_LOC", "MS"
)

WAVEFORM_NAMES = (
    "trapezoid", "ip", "ne", "te", "actuator", "phase"
)

#: charge number of every species the ADAS table carries
ADAS_Z = {
    "W": 74, "B": 5, "He": 2, "Be": 4, "C": 6, "O": 8, "N": 7, "F": 9,
    "Ne": 10, "Al": 13, "Si": 14, "Ar": 18, "Ca": 20, "Fe": 26, "Ni": 28,
    "Kr": 36, "Mo": 42, "Xe": 54, "Li": 3, "H": 1, "D": 1, "T": 1
}

#: mass number of every species the ADAS table carries
ADAS_A = {
    "W": 184, "B": 11, "He": 4, "Be": 9, "C": 12, "O": 16, "N": 14,
    "F": 19, "Ne": 20, "Al": 27, "Si": 28, "Ar": 40, "Ca": 40, "Fe": 56,
    "Ni": 58, "Kr": 84, "Mo": 96, "Xe": 131, "Li": 7, "H": 1, "D": 2,
    "T": 3
}
