"""GENERATED by rust/build.sh — do not edit.

这一份检出**构建出来的制品**是哪一版：`internal`（全功能，含 EAST 等只进内部版
的装置）或 `public`。版别在编译期定死（`FYL-DESIGN-19` A-14），所以它是一个
生成物而不是一个运行时开关——`fylite.notice` 据此决定启动 banner 上说不说
「仅限内部测试」那一句。

★与 `app/assets/runtime-version.js` 的 `FyFactsFlavour` 是**同一次构建写下的
同一个值**，两个宿主各留一份：页面读那一份，Python 读这一份。
★提交进仓的这一份是**缺省构建**的那一版（`internal`，A-14）。
"""
FLAVOUR = "internal"
