"""GENERATED by rust/build.sh from rust/fylite/src/mdsip.rs (@mds-request) — do not edit.

The verb codes `fylite_rs_mds_read` takes, keyed by the spelling the
A-Box binding table uses.  ALL is the `*` subscript sentinel.
"""

VERBS = {
    "raw": 0,
    "data": 1,
    "dim_of": 2,
}

#: `*` in a subscript (i64::MIN).
ALL = -9223372036854775808
