#!/usr/bin/env bash
# 构建 fylite 的**数据层**（`rust/fylite_data/`）。
#
#   ./rust/build.sh              -> libfylite_data.so，装进 python/fylite/_lib/
#   ./rust/build.sh --exe        -> 另外构建单文件桌面查看器 fylite-app
#   ./rust/build.sh --cli        -> 另外构建命令行 fylite-data，装进 python/fylite/_bin/
#   ./rust/build.sh --static     -> HDF5 / netCDF 从源码静态编进 .so（发行给没装库的机器）
#   ./rust/build.sh --no-install    只构建
#
# ★数据层链两个 C 库（libhdf5、libnetcdf；`fylite_data/Cargo.toml` 的 [features] 说明
# 为什么）。缺省动态链接系统库：Debian/Ubuntu `apt install libhdf5-dev libnetcdf-dev`，
# conda `conda install hdf5 netcdf4`。`--static` 走 hdf5-metno-src / netcdf-src 从源码编，
# 第一次要十来分钟。
#
# ★IMAS DD 的结构表（`fylite_data/ids/*.tsv`、`src/ids_tables.rs`）是**提交进仓的生成物**，
# 由 `tools/dd-ids-table.py` 从 DD 的 IDSDef.xml 生成——本脚本不重生成它们。
#
# ★★2026-09-02 这一层从内核仓搬过来。理由写在 `fylite_data/src/lib.rs` 抬头：
# 网络协议与文件格式是**宿主的活**，内核那本自己就是这么写的。源码在本仓是公开的
# ——它是协议编解码，不是物理 IP。
#
# ★内核（`libfylite_kernel.so`）不由本脚本构建：它在私有仓 fylite_kernel，
# 由那边的 `rust/build.sh` 装进本仓的同一个 `_lib/`。两份 `.so`、两条来路、
# 一个目录。
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
CRATE="$DIR/fylite_data"
INSTALL=1
EXE=0
CLI=0
FEATURES=""
for a in "$@"; do
    case "$a" in
        --no-install) INSTALL=0 ;;
        --exe) EXE=1 ;;
        --cli) CLI=1 ;;
        --static) FEATURES="--features static" ;;
        *) echo "unknown option $a" >&2; exit 2 ;;
    esac
done

#: ★与内核同一条加固规矩：开发机路径不进制品。这里源码公开，所以泄漏的不是结构
#: 而只是构建者的目录布局连用户名——仍然不该发出去。
: "${CARGO_HOME:=$HOME/.cargo}"
: "${RUSTUP_HOME:=$HOME/.rustup}"
export RUSTFLAGS="${RUSTFLAGS:-} --remap-path-prefix=$CARGO_HOME=/cargo --remap-path-prefix=$RUSTUP_HOME=/rustup"

echo "[data] cargo build --release $FEATURES ..."
cargo build --release $FEATURES --manifest-path "$CRATE/Cargo.toml"
SO="$CRATE/target/release/libfylite_data.so"
[ -f "$SO" ] || { echo "[data] 没有产出 $SO" >&2; exit 1; }

homes=$(strings -n 6 "$SO" | grep -c "$HOME" || true)
[ "$homes" = 0 ] || { echo "::error:: $SO 里有 $homes 条开发机路径" >&2; exit 1; }
exp=$(nm -D --defined-only "$SO" | grep -c 'fylite_data_' || true)
[ "$exp" -gt 0 ] || { echo "::error:: C ABI 导出没了（strip 过头）" >&2; exit 1; }
echo "[data] harden-ok  $(basename "$SO")  ($exp exports)"

if [ "$INSTALL" = 1 ]; then
    mkdir -p "$ROOT/python/fylite/_lib"
    cp "$SO" "$ROOT/python/fylite/_lib/libfylite_data.so"
    echo "[data] installed -> python/fylite/_lib/libfylite_data.so"
fi

# ★★The mdsip REQUEST contract — the verb codes and the `*` sentinel.
#
# The A-Box binding table (`tools/abox-mds-bind.py`) spells a verb as a string;
# `fylite_rs_mds_read` takes an integer.  That mapping is the seam between them,
# it is three lines long, and three lines is exactly the size that feels safe to
# transcribe by hand — which is how `zerod`'s parameter order came to be spelled
# in three places.  Declared in `src/mdsip.rs` with `@mds-request`, generated
# here into both hosts.
python3 - "$ROOT/python/fylite/_mds_request.py" \
          "$ROOT/app/assets/mds-request.js" \
          "$CRATE/src/mdsip.rs" <<'PYMDS'
import re, sys

src = open(sys.argv[3]).read()
m = re.search(r"pub const REQUEST_VERBS:.*?=\s*\[(.*?)\];", src, re.S)
if not m:
    sys.exit("[build] REQUEST_VERBS not found in mdsip.rs")
verbs = re.findall(r'\("([a-z_]+)",\s*(-?\d+)\)', m.group(1))
if not verbs:
    sys.exit("[build] REQUEST_VERBS parsed empty")
sentinel = "-9223372036854775808"   # i64::MIN, spelled out for both hosts

head = ("GENERATED by rust/build.sh from rust/fylite/src/mdsip.rs "
        "(@mds-request) — do not edit.\n\n"
        "The verb codes `fylite_rs_mds_read` takes, keyed by the spelling the\n"
        "A-Box binding table uses.  ALL is the `*` subscript sentinel.")

with open(sys.argv[1], "w") as f:
    f.write('"""%s\n"""\n\n' % head)
    f.write("VERBS = {\n")
    for n, c in verbs:
        f.write('    "%s": %s,\n' % (n, c))
    f.write("}\n\n#: `*` in a subscript (i64::MIN).\nALL = %s\n" % sentinel)

with open(sys.argv[2], "w") as f:
    f.write("// " + head.replace("\n", "\n// ") + "\n\n")
    f.write("export const MDS_VERBS = Object.freeze({\n")
    for n, c in verbs:
        f.write("  %s: %s,\n" % (n, c))
    f.write("});\n\n// `*` in a subscript (i64::MIN).\n")
    f.write("export const MDS_ALL = %sn;\n" % sentinel)
print("[build] mds request: %d verbs" % len(verbs))
PYMDS
echo "[build] mds request -> python/fylite/_mds_request.py, app/assets/mds-request.js"

if [ "$CLI" = 1 ]; then
    echo "[data] cargo build --release --bin fylite-data ..."
    cargo build --release $FEATURES --bin fylite-data --manifest-path "$CRATE/Cargo.toml"
    if [ "$INSTALL" = 1 ]; then
        mkdir -p "$ROOT/python/fylite/_bin"
        cp "$CRATE/target/release/fylite-data" "$ROOT/python/fylite/_bin/fylite-data"
        echo "[data] installed -> python/fylite/_bin/fylite-data"
    fi
fi

if [ "$EXE" = 1 ]; then
    #: ★查看器把整个 `app/` 编进可执行文件；资源表 `src/bin/app/assets.rs` 是
    #: 生成物（`tools/make-app-embed.mjs`），`include_bytes!` 走 `FYLITE_APP_DIR`。
    #: 搬到本仓之后 `app/` 就在隔壁，所以这里能给出确定的值——从前它是跨仓的。
    export FYLITE_APP_DIR="$ROOT/app"
    echo "[data] cargo build --release --features desktop (fylite-app) ..."
    cargo build --release --features desktop --bin fylite-app \
        --manifest-path "$CRATE/Cargo.toml"
    echo "[data] -> $CRATE/target/release/fylite-app"
fi
echo "[data] done."
