// GENERATED by rust/tools/gen-kernel-abi.py in the KERNEL repo — do not edit.
//
// 内核 C ABI 的调度表：按名调用链进来的静态库（`libfylite_kernel_static.a`）。
// 页面在桌面宿主里把调用交给 `/api/kernel`，这里是那条路的另一端；参数种类
// 表由同一次生成写给页面（`app/assets/kernel-abi.js`），两侧不会各说各的。
//
// ★声明是 `extern "C"`，符号在链接期解析。没有链进静态库的构建**编不过**
// 本文件——所以整个模块挂在 `#[cfg(kernel_static)]` 后面，那个 cfg 由
// `build.rs` 在看见那份 `.a` 时才打开（feature 做不到这件事：它得由调用方
// 在命令行上给，而「这台机器上有没有那份归档」是构建脚本才知道的事）。
#![allow(clippy::too_many_arguments)]

use crate::kernel_call::{Frame, Ret, CallError};

extern "C" {
    fn fylite_ext_abi_version() -> u32;
    fn fylite_rs_abi_version() -> u32;
    fn fylite_rs_bound_deriv(_0: *const f64, _1: *const f64, _2: u64, _3: *mut f64) -> i32;
    fn fylite_rs_bounded_lstsq(_0: *const f64, _1: *const f64, _2: u64, _3: u64, _4: *const f64, _5: *const f64, _6: u64, _7: f64, _8: *mut f64) -> i32;
    fn fylite_rs_channel_weights(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: u64, _5: u64, _6: *mut f64) -> i32;
    fn fylite_rs_contour(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: f64, _8: u64, _9: *mut f64) -> i32;
    fn fylite_rs_core_march_init(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: *const f64, _11: *const f64, _12: *const f64, _13: *const f64, _14: *const f64, _15: u64, _16: u64, _17: f64, _18: f64, _19: f64, _20: f64, _21: f64, _22: f64, _23: u64, _24: f64, _25: u64, _26: f64, _27: f64, _28: f64, _29: f64, _30: f64, _31: f64, _32: u64, _33: i32, _34: i32, _35: i32, _36: *mut f64, _37: u64) -> i32;
    fn fylite_rs_core_march_next(_0: *mut f64, _1: u64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: u64, _10: u64, _11: *mut f64, _12: *mut f64, _13: *mut f64, _14: *mut f64, _15: *mut f64) -> i32;
    fn fylite_rs_core_march_result(_0: *const f64, _1: u64, _2: u64, _3: u64, _4: *mut f64, _5: *mut f64, _6: *mut f64, _7: *mut f64, _8: *mut f64, _9: *mut f64, _10: *mut f64, _11: *mut f64) -> i32;
    fn fylite_rs_core_march_state_len(_0: u64, _1: u64) -> u64;
    fn fylite_rs_deltastar_apply(_0: *const f64, _1: u64, _2: *const f64, _3: u64, _4: *const f64, _5: *mut f64) -> i32;
    fn fylite_rs_direct_integrals(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: *const f64, _8: u64, _9: *const f64, _10: *const f64, _11: u64, _12: *const f64, _13: u64, _14: *mut f64, _15: *mut f64) -> i32;
    fn fylite_rs_dispersion_root(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: f64, _5: f64, _6: f64, _7: f64, _8: *mut f64) -> i32;
    fn fylite_rs_dke_assemble(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: u64, _8: *const f64, _9: u64, _10: u64, _11: u64, _12: f64, _13: f64, _14: i32, _15: *mut f64, _16: u64) -> i32;
    fn fylite_rs_dke_coll(_0: u64, _1: u64, _2: u64, _3: i32, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: i32, _10: *mut f64, _11: u64) -> i32;
    fn fylite_rs_dke_energy(_0: u64, _1: u64, _2: i32, _3: i32, _4: *mut f64, _5: u64) -> i32;
    fn fylite_rs_dke_equil(_0: u64, _1: *const f64, _2: f64, _3: i32, _4: *mut f64, _5: u64) -> i32;
    fn fylite_rs_dke_fcoll(_0: u64, _1: f64, _2: i32, _3: *mut f64, _4: u64) -> i32;
    fn fylite_rs_dke_solve(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: u64, _7: *const f64, _8: u64, _9: u64, _10: u64, _11: f64, _12: f64, _13: f64, _14: f64, _15: *mut f64, _16: u64) -> i32;
    fn fylite_rs_dke_transport(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: u64, _8: *const f64, _9: u64, _10: u64, _11: u64, _12: *const f64, _13: f64, _14: f64, _15: f64, _16: i32, _17: *mut f64, _18: u64) -> i32;
    fn fylite_rs_eigen(_0: *const f64, _1: *const f64, _2: u64, _3: i32, _4: *mut f64, _5: *mut f64, _6: *mut f64, _7: *mut f64) -> i32;
    fn fylite_rs_ellipke(_0: *const f64, _1: u64, _2: *mut f64, _3: *mut f64) -> i32;
    fn fylite_rs_factor_dispersion(_0: *const f64, _1: u64, _2: *mut f64) -> i32;
    fn fylite_rs_fill_filaments(_0: *const f64, _1: *const f64, _2: u64, _3: f64, _4: u64, _5: f64, _6: *mut f64) -> i32;
    fn fylite_rs_flux_match_init(_0: *const f64, _1: u64, _2: u64, _3: f64, _4: f64, _5: f64, _6: u64, _7: i32, _8: f64, _9: *mut f64, _10: u64) -> i32;
    fn fylite_rs_flux_match_next(_0: *mut f64, _1: u64, _2: *const f64, _3: *const f64, _4: u64, _5: *mut f64) -> i32;
    fn fylite_rs_flux_match_result(_0: *const f64, _1: u64, _2: u64, _3: *mut f64, _4: *mut f64, _5: *mut f64, _6: *mut f64, _7: *mut f64) -> i32;
    fn fylite_rs_flux_match_state_len(_0: u64, _1: u64);
    fn fylite_rs_gradient(_0: *const f64, _1: *const f64, _2: u64, _3: i32, _4: f64, _5: *mut f64) -> i32;
    fn fylite_rs_inside_polygon(_0: *const f64, _1: *const f64, _2: u64, _3: *const f64, _4: *const f64, _5: u64, _6: *mut f64) -> i32;
    fn fylite_rs_interp(_0: *const f64, _1: u64, _2: *const f64, _3: *const f64, _4: u64, _5: *mut f64) -> i32;
    fn fylite_rs_label_drift(_0: *const f64, _1: u64, _2: f64, _3: f64, _4: *mut f64) -> i32;
    fn fylite_rs_line_integral(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: f64, _5: *const f64, _6: u64, _7: f64, _8: *const f64, _9: *const f64, _10: u64, _11: f64, _12: i32, _13: *mut f64, _14: *mut f64) -> i32;
    fn fylite_rs_nn_ensemble(_0: u64, _1: u64, _2: u64, _3: u64, _4: u64, _5: i32, _6: u64, _7: *const f64, _8: *const i32, _9: *const f64, _10: *const i32, _11: u64, _12: *const f64, _13: *const f64, _14: *const f64, _15: *const f64, _16: *const f64, _17: u64, _18: *const f64, _19: *mut f64, _20: *mut f64) -> i32;
    fn fylite_rs_nn_weight_count(_0: u64, _1: u64, _2: u64, _3: u64, _4: u64) -> u64;
    fn fylite_rs_pchip(_0: *const f64, _1: *const f64, _2: u64, _3: *const f64, _4: u64, _5: *mut f64) -> i32;
    fn fylite_rs_ping(_0: f64) -> f64;
    fn fylite_rs_psin_along(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: *const f64, _8: *const f64, _9: u64, _10: *mut f64) -> i32;
    fn fylite_rs_quadrature(_0: *const f64, _1: u64, _2: f64, _3: i32, _4: *mut f64) -> i32;
    fn fylite_rs_reintegrate(_0: *const f64, _1: *const f64, _2: u64, _3: f64, _4: i32, _5: *mut f64) -> i32;
    fn fylite_rs_resample_uniform(_0: *const f64, _1: u64, _2: *mut f64, _3: u64) -> i32;
    fn fylite_rs_ridge_lstsq(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: u64, _5: *const f64, _6: *mut f64) -> i32;
    fn fylite_rs_sample(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: *const f64, _8: *const f64, _9: u64, _10: i32, _11: *mut f64) -> i32;
    fn fylite_rs_sample_grid(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: *const f64, _8: *const f64, _9: u64, _10: *mut f64) -> i32;
    fn fylite_rs_scale_by_turns(_0: *mut f64, _1: u64, _2: u64, _3: *const f64, _4: *const f64) -> i32;
    fn fylite_rs_scenario(_0: u32, _1: *const f64, _2: u64, _3: *const f64, _4: u64, _5: *const u64, _6: u64, _7: *mut f64, _8: u64) -> i32;
    fn fylite_rs_scenario_sizes(_0: u32, _1: *const u64, _2: u64, _3: *mut f64) -> i32;
    fn fylite_rs_shell_area(_0: *const f64, _1: *const f64, _2: u64, _3: *const f64, _4: *const f64, _5: *mut f64) -> i32;
    fn fylite_rs_shell_sum(_0: *const f64, _1: *const f64, _2: u64, _3: *mut f64) -> i32;
    fn fylite_rs_shell_table(_0: f64, _1: f64, _2: f64, _3: f64, _4: u64, _5: u64, _6: *const f64, _7: f64, _8: f64, _9: *const f64, _10: *const f64, _11: u64, _12: *const f64, _13: u64, _14: u64, _15: *mut f64) -> i32;
    fn fylite_rs_svd(_0: *const f64, _1: u64, _2: u64, _3: *mut f64, _4: *mut f64, _5: *mut f64) -> i32;
    fn fylite_rs_svd_solve(_0: *const f64, _1: *const f64, _2: u64, _3: u64, _4: f64, _5: i64, _6: *mut f64, _7: *mut f64, _8: *mut f64) -> i32;
    fn fylite_rs_table_ratio_check(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: *const f64, _5: u64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: u64, _11: *mut f64, _12: *mut f64) -> i32;
    fn fylite_rs_tglf_dlnpdr(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: u64, _5: f64, _6: f64, _7: *mut f64) -> i32;
    fn fylite_rs_tglf_flux(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: *const f64, _11: u64, _12: *const f64, _13: u64, _14: u64, _15: u64, _16: i32, _17: *mut f64) -> i32;
    fn fylite_rs_tglf_flux_searched(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: *const f64, _11: u64, _12: *const f64, _13: u64, _14: u64, _15: u64, _16: i32, _17: *const f64, _18: *mut f64) -> i32;
    fn fylite_rs_tglf_kygrid(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: u64, _5: i32, _6: u64, _7: f64, _8: f64, _9: i32, _10: u64, _11: *mut f64) -> i32;
    fn fylite_rs_tglf_linear(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: u64, _11: u64, _12: u64, _13: u64, _14: *mut f64) -> i32;
    fn fylite_rs_tglf_matrices(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: *const f64, _10: u64, _11: u64, _12: u64, _13: i32, _14: *mut f64, _15: *mut f64, _16: u64) -> i32;
    fn fylite_rs_tglf_presets(_0: i32, _1: i32, _2: i32, _3: *mut f64) -> i32;
    fn fylite_rs_tglf_units(_0: *const f64, _1: f64, _2: f64, _3: f64, _4: f64, _5: *mut f64) -> i32;
    fn fylite_rs_to_uniform_extrap(_0: *const f64, _1: *const f64, _2: u64, _3: *mut f64, _4: u64) -> i32;
    fn fylite_rs_two_temperature_init(_0: *const f64, _1: *const f64, _2: *const f64, _3: *const f64, _4: *const f64, _5: *const f64, _6: *const f64, _7: *const f64, _8: *const f64, _9: u64, _10: f64, _11: u64, _12: f64, _13: u64, _14: f64, _15: f64, _16: f64, _17: f64, _18: u64, _19: *mut f64, _20: u64) -> i32;
    fn fylite_rs_two_temperature_next(_0: *mut f64, _1: u64, _2: *const f64, _3: *const f64, _4: *const f64, _5: u64, _6: *mut f64, _7: *mut f64);
    fn fylite_rs_two_temperature_result(_0: *const f64, _1: u64, _2: u64, _3: *mut f64, _4: *mut f64, _5: *mut f64, _6: *mut f64) -> i32;
    fn fylite_rs_two_temperature_state_len(_0: u64) -> u64;
    fn fylite_rs_volume_int(_0: *const f64, _1: *const f64, _2: *const f64, _3: u64, _4: i32, _5: *mut f64) -> i32;
    fn fylite_rs_with_axis_node(_0: *const f64, _1: u64, _2: *const f64, _3: u64, _4: u64, _5: *mut f64, _6: *mut f64) -> i32;
}

/// 这一版桥得过去的符号，按名排序。
pub const BRIDGED: &[&str] = &[
    "fylite_ext_abi_version",
    "fylite_rs_abi_version",
    "fylite_rs_bound_deriv",
    "fylite_rs_bounded_lstsq",
    "fylite_rs_channel_weights",
    "fylite_rs_contour",
    "fylite_rs_core_march_init",
    "fylite_rs_core_march_next",
    "fylite_rs_core_march_result",
    "fylite_rs_core_march_state_len",
    "fylite_rs_deltastar_apply",
    "fylite_rs_direct_integrals",
    "fylite_rs_dispersion_root",
    "fylite_rs_dke_assemble",
    "fylite_rs_dke_coll",
    "fylite_rs_dke_energy",
    "fylite_rs_dke_equil",
    "fylite_rs_dke_fcoll",
    "fylite_rs_dke_solve",
    "fylite_rs_dke_transport",
    "fylite_rs_eigen",
    "fylite_rs_ellipke",
    "fylite_rs_factor_dispersion",
    "fylite_rs_fill_filaments",
    "fylite_rs_flux_match_init",
    "fylite_rs_flux_match_next",
    "fylite_rs_flux_match_result",
    "fylite_rs_flux_match_state_len",
    "fylite_rs_gradient",
    "fylite_rs_inside_polygon",
    "fylite_rs_interp",
    "fylite_rs_label_drift",
    "fylite_rs_line_integral",
    "fylite_rs_nn_ensemble",
    "fylite_rs_nn_weight_count",
    "fylite_rs_pchip",
    "fylite_rs_ping",
    "fylite_rs_psin_along",
    "fylite_rs_quadrature",
    "fylite_rs_reintegrate",
    "fylite_rs_resample_uniform",
    "fylite_rs_ridge_lstsq",
    "fylite_rs_sample",
    "fylite_rs_sample_grid",
    "fylite_rs_scale_by_turns",
    "fylite_rs_scenario",
    "fylite_rs_scenario_sizes",
    "fylite_rs_shell_area",
    "fylite_rs_shell_sum",
    "fylite_rs_shell_table",
    "fylite_rs_svd",
    "fylite_rs_svd_solve",
    "fylite_rs_table_ratio_check",
    "fylite_rs_tglf_dlnpdr",
    "fylite_rs_tglf_flux",
    "fylite_rs_tglf_flux_searched",
    "fylite_rs_tglf_kygrid",
    "fylite_rs_tglf_linear",
    "fylite_rs_tglf_matrices",
    "fylite_rs_tglf_presets",
    "fylite_rs_tglf_units",
    "fylite_rs_to_uniform_extrap",
    "fylite_rs_two_temperature_init",
    "fylite_rs_two_temperature_next",
    "fylite_rs_two_temperature_result",
    "fylite_rs_two_temperature_state_len",
    "fylite_rs_volume_int",
    "fylite_rs_with_axis_node",
];

/// 结构门那几个：**有意不桥**（见生成器抬头）。按名拒绝好过按名放行。
pub const UNBRIDGED: &[&str] = &[
    "fylite_ext_fyo_tree",  // 结构门：参数里有二级指针
    "fylite_rs_alloc",  // 分配与释放属于调用方那一侧
    "fylite_rs_free",  // 分配与释放属于调用方那一侧
    "fylite_rs_fyo",  // 结构门：参数里有二级指针
    "fylite_rs_fyo_tree",  // 结构门：参数里有二级指针
];

/// 每个符号的参数种类，与页面那份表逐格相同。
pub const KINDS: &[(&str, &[&str])] = &[
    ("fylite_ext_abi_version", &[]),
    ("fylite_rs_abi_version", &[]),
    ("fylite_rs_bound_deriv", &["in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_bounded_lstsq", &["in_f64", "in_f64", "u64", "u64", "in_f64", "in_f64", "u64", "f64", "out_f64"]),
    ("fylite_rs_channel_weights", &["in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "out_f64"]),
    ("fylite_rs_contour", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "f64", "u64", "out_f64"]),
    ("fylite_rs_core_march_init", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "f64", "f64", "f64", "f64", "f64", "f64", "u64", "f64", "u64", "f64", "f64", "f64", "f64", "f64", "f64", "u64", "i32", "i32", "i32", "out_f64", "u64"]),
    ("fylite_rs_core_march_next", &["out_f64", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_core_march_result", &["in_f64", "u64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_core_march_state_len", &["u64", "u64"]),
    ("fylite_rs_deltastar_apply", &["in_f64", "u64", "in_f64", "u64", "in_f64", "out_f64"]),
    ("fylite_rs_direct_integrals", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "u64", "in_f64", "in_f64", "u64", "in_f64", "u64", "out_f64", "out_f64"]),
    ("fylite_rs_dispersion_root", &["in_f64", "in_f64", "in_f64", "u64", "f64", "f64", "f64", "f64", "out_f64"]),
    ("fylite_rs_dke_assemble", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "f64", "f64", "i32", "out_f64", "u64"]),
    ("fylite_rs_dke_coll", &["u64", "u64", "u64", "i32", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "i32", "out_f64", "u64"]),
    ("fylite_rs_dke_energy", &["u64", "u64", "i32", "i32", "out_f64", "u64"]),
    ("fylite_rs_dke_equil", &["u64", "in_f64", "f64", "i32", "out_f64", "u64"]),
    ("fylite_rs_dke_fcoll", &["u64", "f64", "i32", "out_f64", "u64"]),
    ("fylite_rs_dke_solve", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "f64", "f64", "f64", "f64", "out_f64", "u64"]),
    ("fylite_rs_dke_transport", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "in_f64", "f64", "f64", "f64", "i32", "out_f64", "u64"]),
    ("fylite_rs_eigen", &["in_f64", "in_f64", "u64", "i32", "out_f64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_ellipke", &["in_f64", "u64", "out_f64", "out_f64"]),
    ("fylite_rs_factor_dispersion", &["in_f64", "u64", "out_f64"]),
    ("fylite_rs_fill_filaments", &["in_f64", "in_f64", "u64", "f64", "u64", "f64", "out_f64"]),
    ("fylite_rs_flux_match_init", &["in_f64", "u64", "u64", "f64", "f64", "f64", "u64", "i32", "f64", "out_f64", "u64"]),
    ("fylite_rs_flux_match_next", &["out_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_flux_match_result", &["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_flux_match_state_len", &["u64", "u64"]),
    ("fylite_rs_gradient", &["in_f64", "in_f64", "u64", "i32", "f64", "out_f64"]),
    ("fylite_rs_inside_polygon", &["in_f64", "in_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_interp", &["in_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_label_drift", &["in_f64", "u64", "f64", "f64", "out_f64"]),
    ("fylite_rs_line_integral", &["in_f64", "in_f64", "in_f64", "u64", "f64", "in_f64", "u64", "f64", "in_f64", "in_f64", "u64", "f64", "i32", "out_f64", "out_f64"]),
    ("fylite_rs_nn_ensemble", &["u64", "u64", "u64", "u64", "u64", "i32", "u64", "in_f64", "in_i32", "in_f64", "in_i32", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "out_f64", "out_f64"]),
    ("fylite_rs_nn_weight_count", &["u64", "u64", "u64", "u64", "u64"]),
    ("fylite_rs_pchip", &["in_f64", "in_f64", "u64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_ping", &["f64"]),
    ("fylite_rs_psin_along", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_quadrature", &["in_f64", "u64", "f64", "i32", "out_f64"]),
    ("fylite_rs_reintegrate", &["in_f64", "in_f64", "u64", "f64", "i32", "out_f64"]),
    ("fylite_rs_resample_uniform", &["in_f64", "u64", "out_f64", "u64"]),
    ("fylite_rs_ridge_lstsq", &["in_f64", "in_f64", "in_f64", "u64", "u64", "in_f64", "out_f64"]),
    ("fylite_rs_sample", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "i32", "out_f64"]),
    ("fylite_rs_sample_grid", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_scale_by_turns", &["out_f64", "u64", "u64", "in_f64", "in_f64"]),
    ("fylite_rs_scenario", &["u32", "in_f64", "u64", "in_f64", "u64", "in_u64", "u64", "out_f64", "u64"]),
    ("fylite_rs_scenario_sizes", &["u32", "in_u64", "u64", "out_f64"]),
    ("fylite_rs_shell_area", &["in_f64", "in_f64", "u64", "in_f64", "in_f64", "out_f64"]),
    ("fylite_rs_shell_sum", &["in_f64", "in_f64", "u64", "out_f64"]),
    ("fylite_rs_shell_table", &["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "f64", "f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "out_f64"]),
    ("fylite_rs_svd", &["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_svd_solve", &["in_f64", "in_f64", "u64", "u64", "f64", "i64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_table_ratio_check", &["in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "out_f64", "out_f64"]),
    ("fylite_rs_tglf_dlnpdr", &["in_f64", "in_f64", "in_f64", "in_f64", "u64", "f64", "f64", "out_f64"]),
    ("fylite_rs_tglf_flux", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "i32", "out_f64"]),
    ("fylite_rs_tglf_flux_searched", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "i32", "in_f64", "out_f64"]),
    ("fylite_rs_tglf_kygrid", &["in_f64", "in_f64", "in_f64", "in_f64", "u64", "i32", "u64", "f64", "f64", "i32", "u64", "out_f64"]),
    ("fylite_rs_tglf_linear", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "u64", "out_f64"]),
    ("fylite_rs_tglf_matrices", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "i32", "out_f64", "out_f64", "u64"]),
    ("fylite_rs_tglf_presets", &["i32", "i32", "i32", "out_f64"]),
    ("fylite_rs_tglf_units", &["in_f64", "f64", "f64", "f64", "f64", "out_f64"]),
    ("fylite_rs_to_uniform_extrap", &["in_f64", "in_f64", "u64", "out_f64", "u64"]),
    ("fylite_rs_two_temperature_init", &["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "f64", "u64", "f64", "u64", "f64", "f64", "f64", "f64", "u64", "out_f64", "u64"]),
    ("fylite_rs_two_temperature_next", &["out_f64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64", "out_f64"]),
    ("fylite_rs_two_temperature_result", &["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64"]),
    ("fylite_rs_two_temperature_state_len", &["u64"]),
    ("fylite_rs_volume_int", &["in_f64", "in_f64", "in_f64", "u64", "i32", "out_f64"]),
    ("fylite_rs_with_axis_node", &["in_f64", "u64", "in_f64", "u64", "u64", "out_f64", "out_f64"]),
];

/// 按名调用一个内核导出。
///
/// ★`f.ptrs()` 先把每一格缓冲的裸指针取出来（各格是各自的分配，互不重叠），
/// 之后读标量只借不可变引用——两者不冲突，而生成的调用一行写完。
pub fn call(name: &str, f: &mut Frame) -> Result<Ret, CallError> {
    let p = f.ptrs();
    let _ = &p;
    Ok(match name {
        "fylite_ext_abi_version" => {
            f.want(&[], name)?;
            Ret::U32(unsafe { fylite_ext_abi_version() })
        }
        "fylite_rs_abi_version" => {
            f.want(&[], name)?;
            Ret::U32(unsafe { fylite_rs_abi_version() })
        }
        "fylite_rs_bound_deriv" => {
            f.want(&["in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_bound_deriv(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *mut f64) })
        }
        "fylite_rs_bounded_lstsq" => {
            f.want(&["in_f64", "in_f64", "u64", "u64", "in_f64", "in_f64", "u64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_bounded_lstsq(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.u64(3)?, p[4] as *const f64, p[5] as *const f64, f.u64(6)?, f.f64(7)?, p[8] as *mut f64) })
        }
        "fylite_rs_channel_weights" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_channel_weights(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *mut f64) })
        }
        "fylite_rs_contour" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_contour(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, f.f64(7)?, f.u64(8)?, p[9] as *mut f64) })
        }
        "fylite_rs_core_march_init" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "f64", "f64", "f64", "f64", "f64", "f64", "u64", "f64", "u64", "f64", "f64", "f64", "f64", "f64", "f64", "u64", "i32", "i32", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_core_march_init(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, p[10] as *const f64, p[11] as *const f64, p[12] as *const f64, p[13] as *const f64, p[14] as *const f64, f.u64(15)?, f.u64(16)?, f.f64(17)?, f.f64(18)?, f.f64(19)?, f.f64(20)?, f.f64(21)?, f.f64(22)?, f.u64(23)?, f.f64(24)?, f.u64(25)?, f.f64(26)?, f.f64(27)?, f.f64(28)?, f.f64(29)?, f.f64(30)?, f.f64(31)?, f.u64(32)?, f.i32(33)?, f.i32(34)?, f.i32(35)?, p[36] as *mut f64, f.u64(37)?) })
        }
        "fylite_rs_core_march_next" => {
            f.want(&["out_f64", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_core_march_next(p[0] as *mut f64, f.u64(1)?, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.u64(9)?, f.u64(10)?, p[11] as *mut f64, p[12] as *mut f64, p[13] as *mut f64, p[14] as *mut f64, p[15] as *mut f64) })
        }
        "fylite_rs_core_march_result" => {
            f.want(&["in_f64", "u64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_core_march_result(p[0] as *const f64, f.u64(1)?, f.u64(2)?, f.u64(3)?, p[4] as *mut f64, p[5] as *mut f64, p[6] as *mut f64, p[7] as *mut f64, p[8] as *mut f64, p[9] as *mut f64, p[10] as *mut f64, p[11] as *mut f64) })
        }
        "fylite_rs_core_march_state_len" => {
            f.want(&["u64", "u64"], name)?;
            Ret::U64(unsafe { fylite_rs_core_march_state_len(f.u64(0)?, f.u64(1)?) })
        }
        "fylite_rs_deltastar_apply" => {
            f.want(&["in_f64", "u64", "in_f64", "u64", "in_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_deltastar_apply(p[0] as *const f64, f.u64(1)?, p[2] as *const f64, f.u64(3)?, p[4] as *const f64, p[5] as *mut f64) })
        }
        "fylite_rs_direct_integrals" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "u64", "in_f64", "in_f64", "u64", "in_f64", "u64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_direct_integrals(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, p[7] as *const f64, f.u64(8)?, p[9] as *const f64, p[10] as *const f64, f.u64(11)?, p[12] as *const f64, f.u64(13)?, p[14] as *mut f64, p[15] as *mut f64) })
        }
        "fylite_rs_dispersion_root" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "f64", "f64", "f64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_dispersion_root(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, f.f64(4)?, f.f64(5)?, f.f64(6)?, f.f64(7)?, p[8] as *mut f64) })
        }
        "fylite_rs_dke_assemble" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "f64", "f64", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_assemble(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, f.u64(7)?, p[8] as *const f64, f.u64(9)?, f.u64(10)?, f.u64(11)?, f.f64(12)?, f.f64(13)?, f.i32(14)?, p[15] as *mut f64, f.u64(16)?) })
        }
        "fylite_rs_dke_coll" => {
            f.want(&["u64", "u64", "u64", "i32", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_coll(f.u64(0)?, f.u64(1)?, f.u64(2)?, f.i32(3)?, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.i32(9)?, p[10] as *mut f64, f.u64(11)?) })
        }
        "fylite_rs_dke_energy" => {
            f.want(&["u64", "u64", "i32", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_energy(f.u64(0)?, f.u64(1)?, f.i32(2)?, f.i32(3)?, p[4] as *mut f64, f.u64(5)?) })
        }
        "fylite_rs_dke_equil" => {
            f.want(&["u64", "in_f64", "f64", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_equil(f.u64(0)?, p[1] as *const f64, f.f64(2)?, f.i32(3)?, p[4] as *mut f64, f.u64(5)?) })
        }
        "fylite_rs_dke_fcoll" => {
            f.want(&["u64", "f64", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_fcoll(f.u64(0)?, f.f64(1)?, f.i32(2)?, p[3] as *mut f64, f.u64(4)?) })
        }
        "fylite_rs_dke_solve" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "f64", "f64", "f64", "f64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_solve(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, f.u64(6)?, p[7] as *const f64, f.u64(8)?, f.u64(9)?, f.u64(10)?, f.f64(11)?, f.f64(12)?, f.f64(13)?, f.f64(14)?, p[15] as *mut f64, f.u64(16)?) })
        }
        "fylite_rs_dke_transport" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "in_f64", "f64", "f64", "f64", "i32", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_dke_transport(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, f.u64(7)?, p[8] as *const f64, f.u64(9)?, f.u64(10)?, f.u64(11)?, p[12] as *const f64, f.f64(13)?, f.f64(14)?, f.f64(15)?, f.i32(16)?, p[17] as *mut f64, f.u64(18)?) })
        }
        "fylite_rs_eigen" => {
            f.want(&["in_f64", "in_f64", "u64", "i32", "out_f64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_eigen(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.i32(3)?, p[4] as *mut f64, p[5] as *mut f64, p[6] as *mut f64, p[7] as *mut f64) })
        }
        "fylite_rs_ellipke" => {
            f.want(&["in_f64", "u64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_ellipke(p[0] as *const f64, f.u64(1)?, p[2] as *mut f64, p[3] as *mut f64) })
        }
        "fylite_rs_factor_dispersion" => {
            f.want(&["in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_factor_dispersion(p[0] as *const f64, f.u64(1)?, p[2] as *mut f64) })
        }
        "fylite_rs_fill_filaments" => {
            f.want(&["in_f64", "in_f64", "u64", "f64", "u64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_fill_filaments(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.f64(3)?, f.u64(4)?, f.f64(5)?, p[6] as *mut f64) })
        }
        "fylite_rs_flux_match_init" => {
            f.want(&["in_f64", "u64", "u64", "f64", "f64", "f64", "u64", "i32", "f64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_flux_match_init(p[0] as *const f64, f.u64(1)?, f.u64(2)?, f.f64(3)?, f.f64(4)?, f.f64(5)?, f.u64(6)?, f.i32(7)?, f.f64(8)?, p[9] as *mut f64, f.u64(10)?) })
        }
        "fylite_rs_flux_match_next" => {
            f.want(&["out_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_flux_match_next(p[0] as *mut f64, f.u64(1)?, p[2] as *const f64, p[3] as *const f64, f.u64(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_flux_match_result" => {
            f.want(&["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_flux_match_result(p[0] as *const f64, f.u64(1)?, f.u64(2)?, p[3] as *mut f64, p[4] as *mut f64, p[5] as *mut f64, p[6] as *mut f64, p[7] as *mut f64) })
        }
        "fylite_rs_flux_match_state_len" => {
            f.want(&["u64", "u64"], name)?;
            unsafe { fylite_rs_flux_match_state_len(f.u64(0)?, f.u64(1)?) };
            Ret::Unit
        }
        "fylite_rs_gradient" => {
            f.want(&["in_f64", "in_f64", "u64", "i32", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_gradient(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.i32(3)?, f.f64(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_inside_polygon" => {
            f.want(&["in_f64", "in_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_inside_polygon(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *const f64, p[4] as *const f64, f.u64(5)?, p[6] as *mut f64) })
        }
        "fylite_rs_interp" => {
            f.want(&["in_f64", "u64", "in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_interp(p[0] as *const f64, f.u64(1)?, p[2] as *const f64, p[3] as *const f64, f.u64(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_label_drift" => {
            f.want(&["in_f64", "u64", "f64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_label_drift(p[0] as *const f64, f.u64(1)?, f.f64(2)?, f.f64(3)?, p[4] as *mut f64) })
        }
        "fylite_rs_line_integral" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "f64", "in_f64", "u64", "f64", "in_f64", "in_f64", "u64", "f64", "i32", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_line_integral(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, f.f64(4)?, p[5] as *const f64, f.u64(6)?, f.f64(7)?, p[8] as *const f64, p[9] as *const f64, f.u64(10)?, f.f64(11)?, f.i32(12)?, p[13] as *mut f64, p[14] as *mut f64) })
        }
        "fylite_rs_nn_ensemble" => {
            f.want(&["u64", "u64", "u64", "u64", "u64", "i32", "u64", "in_f64", "in_i32", "in_f64", "in_i32", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_nn_ensemble(f.u64(0)?, f.u64(1)?, f.u64(2)?, f.u64(3)?, f.u64(4)?, f.i32(5)?, f.u64(6)?, p[7] as *const f64, p[8] as *const i32, p[9] as *const f64, p[10] as *const i32, f.u64(11)?, p[12] as *const f64, p[13] as *const f64, p[14] as *const f64, p[15] as *const f64, p[16] as *const f64, f.u64(17)?, p[18] as *const f64, p[19] as *mut f64, p[20] as *mut f64) })
        }
        "fylite_rs_nn_weight_count" => {
            f.want(&["u64", "u64", "u64", "u64", "u64"], name)?;
            Ret::U64(unsafe { fylite_rs_nn_weight_count(f.u64(0)?, f.u64(1)?, f.u64(2)?, f.u64(3)?, f.u64(4)?) })
        }
        "fylite_rs_pchip" => {
            f.want(&["in_f64", "in_f64", "u64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_pchip(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *const f64, f.u64(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_ping" => {
            f.want(&["f64"], name)?;
            Ret::F64(unsafe { fylite_rs_ping(f.f64(0)?) })
        }
        "fylite_rs_psin_along" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_psin_along(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.u64(9)?, p[10] as *mut f64) })
        }
        "fylite_rs_quadrature" => {
            f.want(&["in_f64", "u64", "f64", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_quadrature(p[0] as *const f64, f.u64(1)?, f.f64(2)?, f.i32(3)?, p[4] as *mut f64) })
        }
        "fylite_rs_reintegrate" => {
            f.want(&["in_f64", "in_f64", "u64", "f64", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_reintegrate(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.f64(3)?, f.i32(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_resample_uniform" => {
            f.want(&["in_f64", "u64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_resample_uniform(p[0] as *const f64, f.u64(1)?, p[2] as *mut f64, f.u64(3)?) })
        }
        "fylite_rs_ridge_lstsq" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "u64", "in_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_ridge_lstsq(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, f.u64(4)?, p[5] as *const f64, p[6] as *mut f64) })
        }
        "fylite_rs_sample" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_sample(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.u64(9)?, f.i32(10)?, p[11] as *mut f64) })
        }
        "fylite_rs_sample_grid" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_sample_grid(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.u64(9)?, p[10] as *mut f64) })
        }
        "fylite_rs_scale_by_turns" => {
            f.want(&["out_f64", "u64", "u64", "in_f64", "in_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_scale_by_turns(p[0] as *mut f64, f.u64(1)?, f.u64(2)?, p[3] as *const f64, p[4] as *const f64) })
        }
        "fylite_rs_scenario" => {
            f.want(&["u32", "in_f64", "u64", "in_f64", "u64", "in_u64", "u64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_scenario(f.u32(0)?, p[1] as *const f64, f.u64(2)?, p[3] as *const f64, f.u64(4)?, p[5] as *const u64, f.u64(6)?, p[7] as *mut f64, f.u64(8)?) })
        }
        "fylite_rs_scenario_sizes" => {
            f.want(&["u32", "in_u64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_scenario_sizes(f.u32(0)?, p[1] as *const u64, f.u64(2)?, p[3] as *mut f64) })
        }
        "fylite_rs_shell_area" => {
            f.want(&["in_f64", "in_f64", "u64", "in_f64", "in_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_shell_area(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *const f64, p[4] as *const f64, p[5] as *mut f64) })
        }
        "fylite_rs_shell_sum" => {
            f.want(&["in_f64", "in_f64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_shell_sum(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *mut f64) })
        }
        "fylite_rs_shell_table" => {
            f.want(&["f64", "f64", "f64", "f64", "u64", "u64", "in_f64", "f64", "f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_shell_table(f.f64(0)?, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.u64(4)?, f.u64(5)?, p[6] as *const f64, f.f64(7)?, f.f64(8)?, p[9] as *const f64, p[10] as *const f64, f.u64(11)?, p[12] as *const f64, f.u64(13)?, f.u64(14)?, p[15] as *mut f64) })
        }
        "fylite_rs_svd" => {
            f.want(&["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_svd(p[0] as *const f64, f.u64(1)?, f.u64(2)?, p[3] as *mut f64, p[4] as *mut f64, p[5] as *mut f64) })
        }
        "fylite_rs_svd_solve" => {
            f.want(&["in_f64", "in_f64", "u64", "u64", "f64", "i64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_svd_solve(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, f.u64(3)?, f.f64(4)?, f.i64(5)?, p[6] as *mut f64, p[7] as *mut f64, p[8] as *mut f64) })
        }
        "fylite_rs_table_ratio_check" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_table_ratio_check(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, p[4] as *const f64, f.u64(5)?, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, f.u64(10)?, p[11] as *mut f64, p[12] as *mut f64) })
        }
        "fylite_rs_tglf_dlnpdr" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "u64", "f64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_dlnpdr(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, f.u64(4)?, f.f64(5)?, f.f64(6)?, p[7] as *mut f64) })
        }
        "fylite_rs_tglf_flux" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_flux(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, p[10] as *const f64, f.u64(11)?, p[12] as *const f64, f.u64(13)?, f.u64(14)?, f.u64(15)?, f.i32(16)?, p[17] as *mut f64) })
        }
        "fylite_rs_tglf_flux_searched" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "in_f64", "u64", "u64", "u64", "i32", "in_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_flux_searched(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, p[10] as *const f64, f.u64(11)?, p[12] as *const f64, f.u64(13)?, f.u64(14)?, f.u64(15)?, f.i32(16)?, p[17] as *const f64, p[18] as *mut f64) })
        }
        "fylite_rs_tglf_kygrid" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "u64", "i32", "u64", "f64", "f64", "i32", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_kygrid(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, f.u64(4)?, f.i32(5)?, f.u64(6)?, f.f64(7)?, f.f64(8)?, f.i32(9)?, f.u64(10)?, p[11] as *mut f64) })
        }
        "fylite_rs_tglf_linear" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "u64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_linear(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, f.u64(10)?, f.u64(11)?, f.u64(12)?, f.u64(13)?, p[14] as *mut f64) })
        }
        "fylite_rs_tglf_matrices" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "u64", "u64", "i32", "out_f64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_matrices(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, p[9] as *const f64, f.u64(10)?, f.u64(11)?, f.u64(12)?, f.i32(13)?, p[14] as *mut f64, p[15] as *mut f64, f.u64(16)?) })
        }
        "fylite_rs_tglf_presets" => {
            f.want(&["i32", "i32", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_presets(f.i32(0)?, f.i32(1)?, f.i32(2)?, p[3] as *mut f64) })
        }
        "fylite_rs_tglf_units" => {
            f.want(&["in_f64", "f64", "f64", "f64", "f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_tglf_units(p[0] as *const f64, f.f64(1)?, f.f64(2)?, f.f64(3)?, f.f64(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_to_uniform_extrap" => {
            f.want(&["in_f64", "in_f64", "u64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_to_uniform_extrap(p[0] as *const f64, p[1] as *const f64, f.u64(2)?, p[3] as *mut f64, f.u64(4)?) })
        }
        "fylite_rs_two_temperature_init" => {
            f.want(&["in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "in_f64", "u64", "f64", "u64", "f64", "u64", "f64", "f64", "f64", "f64", "u64", "out_f64", "u64"], name)?;
            Ret::I32(unsafe { fylite_rs_two_temperature_init(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, p[5] as *const f64, p[6] as *const f64, p[7] as *const f64, p[8] as *const f64, f.u64(9)?, f.f64(10)?, f.u64(11)?, f.f64(12)?, f.u64(13)?, f.f64(14)?, f.f64(15)?, f.f64(16)?, f.f64(17)?, f.u64(18)?, p[19] as *mut f64, f.u64(20)?) })
        }
        "fylite_rs_two_temperature_next" => {
            f.want(&["out_f64", "u64", "in_f64", "in_f64", "in_f64", "u64", "out_f64", "out_f64"], name)?;
            unsafe { fylite_rs_two_temperature_next(p[0] as *mut f64, f.u64(1)?, p[2] as *const f64, p[3] as *const f64, p[4] as *const f64, f.u64(5)?, p[6] as *mut f64, p[7] as *mut f64) };
            Ret::Unit
        }
        "fylite_rs_two_temperature_result" => {
            f.want(&["in_f64", "u64", "u64", "out_f64", "out_f64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_two_temperature_result(p[0] as *const f64, f.u64(1)?, f.u64(2)?, p[3] as *mut f64, p[4] as *mut f64, p[5] as *mut f64, p[6] as *mut f64) })
        }
        "fylite_rs_two_temperature_state_len" => {
            f.want(&["u64"], name)?;
            Ret::U64(unsafe { fylite_rs_two_temperature_state_len(f.u64(0)?) })
        }
        "fylite_rs_volume_int" => {
            f.want(&["in_f64", "in_f64", "in_f64", "u64", "i32", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_volume_int(p[0] as *const f64, p[1] as *const f64, p[2] as *const f64, f.u64(3)?, f.i32(4)?, p[5] as *mut f64) })
        }
        "fylite_rs_with_axis_node" => {
            f.want(&["in_f64", "u64", "in_f64", "u64", "u64", "out_f64", "out_f64"], name)?;
            Ret::I32(unsafe { fylite_rs_with_axis_node(p[0] as *const f64, f.u64(1)?, p[2] as *const f64, f.u64(3)?, f.u64(4)?, p[5] as *mut f64, p[6] as *mut f64) })
        }
        _ => return Err(CallError::NoSuchSymbol(name.to_string())),
    })
}
