"""`machine_desc/` holds device descriptions the package can actually read.

★★**Why this exists.**  Until 2026-08-22 this repository could describe one
machine on the Python side (EAST) and a second one only as a browser asset
(`app/assets/dev-iter.js`), in a shape nothing in `fylite` reads.  So "which
machines does fylite know?" had two answers in two formats, and the answer a
Python caller could use was one.

The six machines converged out of fydata are documents now, generated by
`tools/fydata-to-fyo-device.py`.  A generated file that nobody loads is
decoration, and a generated file nobody re-derives drifts from its source —
so this gate does both: every document goes through the real reader
(`device.load_device`, contract check included), and where fydata is on hand
the generator is re-run and its output diffed against what is committed.

★No physics is asserted here and none belongs: this is about whether a
description can be READ and whether it still matches the tree it came from.
The one numerical case is a cross-check between two descriptions of the SAME
machine that must not disagree — the ITER document and the browser asset,
both derived from the same fydata files.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from fylite import device

ROOT = Path(__file__).resolve().parents[2]
DESC = ROOT / "machine_desc"
FYDATA_ENV = "FYDATA_DIR"

#: EAST is hand-maintained; every other document is generated.
HANDWRITTEN = {"east"}

DOCS = sorted(DESC.glob("*/*_device.yaml"))

pytestmark = pytest.mark.skipif(not DOCS, reason="no machine_desc/ in this tree")


def _ids(p: Path) -> str:
    return p.parent.name


@pytest.mark.parametrize("doc", DOCS, ids=_ids)
def test_every_description_loads_through_the_real_reader(doc: Path):
    """★`load_device`, not `yaml.safe_load`: the contract is the point.

    It refuses a document with no semantic header and one that is missing an
    IDS group, which is exactly what a half-converted machine looks like.
    """
    dev = device.load_device(doc)
    assert dev["@type"] == "fyo:DeviceDescription"
    assert dev["@id"].endswith(f"device/{_ids(doc)}") or _ids(doc) == "east"
    for group in device.DEVICE_REQUIRED:
        assert group in dev, group


@pytest.mark.parametrize("doc", [d for d in DOCS if _ids(d) not in HANDWRITTEN],
                         ids=_ids)
def test_a_group_with_no_upstream_data_says_so(doc: Path):
    """★★An IDS group that carries nothing must SAY it carries nothing.

    The required-group check exists because a document quietly missing
    `pf_active` yields a machine with no coils rather than an error.  Writing
    an empty group to satisfy that check would put the silence back — so an
    empty group here has to carry `fylite:absent` with a reason, and a
    non-empty one must not claim to be absent.
    """
    dev = device.load_device(doc)
    bad = []
    for group in ("magnetics", "pf_active", "wall", "interferometer",
                  "polarimeter", "data_source", "operational", "solver_dims"):
        node = dev[group]
        absent = isinstance(node, dict) and "fylite:absent" in node
        content = _has_content(group, node)
        if content and absent:
            bad.append(f"{group}: marked absent but carries data")
        if not content and not absent:
            bad.append(f"{group}: empty and says nothing about why")
    assert not bad, f"{doc.relative_to(ROOT)}:\n  " + "\n  ".join(bad)


def _has_content(group: str, node) -> bool:
    if not isinstance(node, dict):
        return bool(node)
    #: ★the DD's ARRAYS, which is the canonical spelling (`@fyo-table
    #: DEVICE`).  These read `{count, channel}` and a mapping `description_2d`
    #: for one batch — the two dialects this table exists to collapse.
    if group == "magnetics":
        return any(node.get(k) for k in ("flux_loop", "b_field_pol_probe"))
    if group == "pf_active":
        return bool(node.get("coil"))
    if group == "wall":
        d2 = node.get("description_2d") or [{}]
        return bool(d2[0].get("limiter", {}).get("unit"))
    if group in ("interferometer", "polarimeter"):
        return bool(node.get("channel"))
    #: `data_source` / `operational` / `solver_dims` carry no array — any key
    #: that is not the header or the absence marker is content.
    return any(not k.startswith(("@", "fylite:absent")) for k in node)


@pytest.mark.parametrize("doc", [d for d in DOCS if _ids(d) not in HANDWRITTEN],
                         ids=_ids)
def test_every_generated_group_names_the_file_it_came_from(doc: Path):
    """A converted group carries `fylite:source`, and it resolves in fydata.

    ★The path is checked as a STRING even when fydata is absent: a
    provenance line that names nothing is the failure mode a converter has,
    and it does not need the source tree present to be caught.
    """
    dev = device.load_device(doc)
    named = [dev[g].get("fylite:source") for g in ("magnetics", "pf_active", "wall")
             if _has_content(g, dev[g])]
    assert named, f"{doc.relative_to(ROOT)} converted nothing at all"
    #: ★both spellings, deliberately.  fydata renamed its top directory
    #: `machine/` -> `device/` on 2026-09-02; the committed documents were
    #: derived before that and say `machine/`, a fresh run says `device/`.
    #: Pinning either one alone would turn「这批文档比改名早」into a red gate,
    #: which is not what this assertion is for — it is here to catch a
    #: provenance line that names NOTHING.
    #: ★★2026-09-02 再加一种：权威源改成 **fydoc**（用户裁定），它的布局是
    #: `device/<id>/abox/…`，不是 fydata 的 `…/tokamak/<id>/…`。三种都认，
    #: 判的仍是同一件事——这一行有没有指向某个具体文件。
    for src in named:
        assert src and re.match(
            r"(?:(?:machine|device)/tokamak/\w+/|device/\w+/abox/)", str(src)), src


def _fydata() -> Path:
    root = os.environ.get(FYDATA_ENV)
    if not root:
        pytest.skip(f"set ${FYDATA_ENV} to a fydata checkout to re-derive "
                    "the generated device descriptions")
    p = Path(root).expanduser()
    if not (p / "device" / "tokamak").is_dir():
        pytest.skip(f"${FYDATA_ENV}={p} does not look like a fydata checkout")
    return p


def test_the_generated_descriptions_still_match_their_source(tmp_path):
    """★★Re-run the generator and diff — the only thing that keeps a
    generated file honest.

    A converted document is a claim about somebody else's tree.  Committing
    it and never re-deriving it means the day upstream changes a coil, this
    repository keeps describing the old machine with a provenance block that
    says otherwise — which is worse than having no description, because it
    reads as sourced.

    ★What this gate must NOT do is confuse「上游改了」with「这份检出里没有那台
    机器」.  fydata checkouts differ, and only the machines whose manifest is
    present in THIS one can be re-derived; the rest are reported as not
    checked and left alone.  Calling them drift would tell the reader to
    re-run and commit, and that would delete their documents.
    """
    fydata = _fydata()
    gen = ROOT / "tools" / "fydata-to-fyo-device.py"
    r = subprocess.run([sys.executable, str(gen), "--all",
                        "--fydata", str(fydata), "-o", str(tmp_path)],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    #: ★★WHICH MACHINES THIS CHECKOUT CAN SPEAK FOR.  A machine is derivable
    #: only if the tree carries its manifest; a checkout that does not have
    #: one cannot say anything about the committed document, and「生成器不再
    #: 产出它」would be a false accusation.  ★Measured 2026-08-26: a fydata
    #: checkout at c61b408 carries a manifest for EAST alone, so this gate
    #: reported six machines as drifted and told the reader to re-run and
    #: commit — which would have DELETED six device descriptions.  A gate
    #: whose remedy destroys data on a partial checkout is worse than no gate.
    have = {q.parent.name
            for q in (fydata / "device" / "tokamak").glob("*/machine.yaml")}
    drift, absent = [], []
    for doc in DOCS:
        ids = _ids(doc)
        if ids in HANDWRITTEN:
            continue
        if ids not in have:
            absent.append(ids)
            continue
        fresh = tmp_path / ids / doc.name
        if not fresh.is_file():
            drift.append(f"{ids}: its manifest is in this checkout and the "
                         "generator still emitted nothing")
        elif fresh.read_text(encoding="utf-8") != doc.read_text(encoding="utf-8"):
            drift.append(f"{ids}: committed file differs from a fresh run")
    if absent:
        #: said out loud, never silently: a reader has to know the gate
        #: checked less than the whole set, and exactly how much less
        print(f"\n  not derivable from ${FYDATA_ENV}={fydata} (no manifest "
              f"in that checkout, so not checked): {sorted(absent)}")
    #: ★and the gate must still have checked SOMETHING — a checkout carrying
    #: no manifest at all would otherwise pass by having nothing to compare
    assert have, (
        f"${FYDATA_ENV}={fydata} carries no machine manifest at all; this "
        "gate would pass by having nothing to check")
    assert not drift, (
        "re-run `python3 tools/fydata-to-fyo-device.py --all` and commit:\n  "
        + "\n  ".join(drift))


def test_the_generator_refuses_to_overwrite_the_hand_written_east_document(tmp_path):
    """★EAST's document is strictly richer than fydata's EAST tree — the est2
    79-probe basis, the fit-control block, the passive set and the supply
    parameters have no upstream at all.  A generator that would answer for it
    is a generator that can delete all of that in one run."""
    fydata = _fydata()
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "fydata-to-fyo-device.py"),
                        "east", "--fydata", str(fydata), "-o", str(tmp_path)],
                       capture_output=True, text=True)
    assert r.returncode != 0, "it produced an EAST document"
    assert "refusing to overwrite" in r.stderr
    assert not list(tmp_path.glob("**/*.yaml"))


#: ★★2026-09-02：`fylite_device_<id>.json` 是**手工件**——全仓没有任何工具产出
#: 它，而内核仓的 `machine_desc/` 已废弃，拖回工具只出 `<id>_device.yaml`。所以
#: 这一族在今天的检出上通常是空的，下面几条随之 skip 并点名缺的是什么，与本仓
#: 其它「需要机器数据」的判据同一套政策。★它们不是被删掉：这几份文档一旦有了
#: 正式的家（多半是 fydata），把它拖回来这几条就自己回来。
APP_DOCS = sorted(DESC.glob("*/fylite_device_*.json"))


def test_every_generated_browser_document_still_matches_its_source(tmp_path):
    """★The browser document is a COPY of the fyo one, so it can go stale.

    `tools/fyo-device-to-app.py` reads the fyo description through the
    declared field table and writes the page's import document.  A copy that
    is committed and never re-derived is the same hazard the fydata
    conversion has one level up — and this repository has just paid for it
    once, in EAST's wall.
    """
    gen = ROOT / "tools" / "fyo-device-to-app.py"
    made = [p for p in APP_DOCS if _ids(p) not in HANDWRITTEN]
    if not made:
        pytest.skip("no generated browser document in this tree")
    r = subprocess.run([sys.executable, str(gen), "--all", "-o", str(tmp_path)],
                       capture_output=True, text=True, cwd=str(ROOT))
    #: ★a non-zero exit is EXPECTED here: three machines are refused for
    #: want of a limiter, coils or a vacuum field.  What matters is that the
    #: ones it does emit match.
    drift = []
    for doc in made:
        fresh = tmp_path / _ids(doc) / doc.name
        if not fresh.is_file():
            drift.append(f"{_ids(doc)}: the generator no longer emits it "
                         f"({r.stderr.strip().splitlines()[-1] if r.stderr else ''})")
        elif fresh.read_text(encoding="utf-8") != doc.read_text(encoding="utf-8"):
            drift.append(f"{_ids(doc)}: committed file differs from a fresh run")
    assert not drift, (
        "re-run `python3 tools/fyo-device-to-app.py --all` and commit:\n  "
        + "\n  ".join(drift))


@pytest.mark.parametrize("doc", APP_DOCS, ids=_ids)
def test_a_browser_document_says_which_machine_it_is(doc: Path):
    """★`fylite:device_id` is what the page resolves `?device=<id>` against;
    without it an imported machine arrives called "imported"."""
    d = json.loads(doc.read_text(encoding="utf-8"))
    assert d["@type"] == "fylite:DeviceDescription/1"
    assert d["fylite:device_id"] == _ids(doc)


# --------------------------------------------------------------------------- #
# one machine, two descriptions                                               #
# --------------------------------------------------------------------------- #
ITER_DOC = DESC / "iter" / "iter_device.yaml"
PRESETS = ROOT / "app" / "devices"
CATALOGUE = PRESETS / "catalogue.jsonld"


@pytest.mark.skipif(not CATALOGUE.is_file(), reason="this tree ships no presets")
@pytest.mark.skipif(
    not APP_DOCS,
    reason="没有 machine_desc/<id>/fylite_device_<id>.json —— 那是**手工件**，"
           "全仓没有任何工具产出它；内核仓的 machine_desc/ 2026-09-02 废弃后，"
           "拖回工具只出 <id>_device.yaml。这几份文档有了正式的家之后这条自己回来")
def test_every_preset_is_the_import_document_it_claims_to_be():
    """★★A preset is the machine's import document, published — a byte-for-byte
    copy of `machine_desc/<id>/fylite_device_<id>.json`.

    A copy, so it can go stale, so it is diffed here.  ★And a COPY rather
    than a regeneration because one of them is not generated at all: EAST's
    import document is hand-completed (`tools/make-east-inputs.py` writes the
    79 probes into it).  Comparing against the import document makes "the
    preset is that machine" one check for every machine instead of two rules;
    where the import document itself comes from is checked next door.
    """
    cat = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    entries = cat.get("fylite:devices") or []
    assert entries, "the catalogue lists no preset"
    drift = []
    for e in entries:
        dev_id, name = e["fylite:device_id"], e["fylite:document"]
        shipped = PRESETS / name
        source = DESC / dev_id / f"fylite_device_{dev_id}.json"
        if not shipped.is_file():
            drift.append(f"{name}: listed in the catalogue and absent")
        elif not source.is_file():
            drift.append(f"{dev_id}: no import document to be a copy of")
        elif shipped.read_text(encoding="utf-8") != source.read_text(encoding="utf-8"):
            drift.append(f"{name}: differs from {source.relative_to(ROOT)}")
    assert not drift, (
        "re-run `python3 tools/fyo-device-to-app.py --all --preset "
        "-o app/devices` and commit:\n  " + "\n  ".join(drift))


@pytest.mark.skipif(not CATALOGUE.is_file(), reason="this tree ships no presets")
def test_every_preset_says_where_its_numbers_came_from():
    """★★`app/` is published, so a preset is a REDISTRIBUTION — and the one
    thing a redistribution must not do is arrive anonymous.

    ★This checks that provenance is DECLARED, not that it is a publication.
    Whether a given machine may be published is a decision this repository
    records rather than makes: `east` is an operator's own description with a
    real discharge in it and is a preset by explicit decision (2026-08-22);
    `cfetr` and `best` rested on private communications and were withdrawn on
    2026-09-01, which the catalogue records under `fylite:not_presets` beside
    every other machine it does not ship.  What a gate can hold is that each
    published machine says where its numbers came from — a reader who finds a
    coil geometry on the public site can trace it to a named source, and a
    machine added later cannot slip in without one.
    """
    cat = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    bad = []
    for e in cat.get("fylite:devices") or []:
        src = e.get("prov:wasDerivedFrom")
        if not src or not all(isinstance(x, str) and len(x) > 20 for x in src):
            bad.append(f"{e.get('fylite:device_id')}: no prov:wasDerivedFrom")
        #: a machine carrying somebody's measured shot must SAY it does
        if e.get("fylite:reference_discharge") \
                and not e.get("fylite:reference_discharge_note"):
            bad.append(f"{e.get('fylite:device_id')}: ships a reference "
                       f"discharge and does not say so")
    assert not bad, "preset provenance:\n  " + "\n  ".join(bad)


@pytest.mark.skipif(not CATALOGUE.is_file(), reason="this tree ships no presets")
def test_the_catalogue_and_the_directory_agree():
    """★A document in `app/devices/` that the catalogue does not list is a
    machine being published with nothing recording where it came from —
    which is the failure mode the catalogue exists to prevent, arriving by
    the back door."""
    cat = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    listed = {e["fylite:document"] for e in cat.get("fylite:devices") or []}
    present = {p.name for p in PRESETS.glob("*.jsonld")} - {"catalogue.jsonld"}
    assert present == listed, {"in the directory only": sorted(present - listed),
                               "in the catalogue only": sorted(listed - present)}


@pytest.mark.skipif(not (ITER_DOC.is_file() and (PRESETS / "iter.jsonld").is_file()),
                    reason="no ITER description on both sides")
def test_the_iter_document_and_the_browser_preset_are_the_same_machine():
    """★★Two files describe ITER — this document and the browser's
    `dev-iter.js` — and both are generated from the same fydata files by
    different tools.  Two derivations of one machine that nothing compares
    will diverge on the first change to either generator, and the page and
    the Python side would then disagree about where a coil is with no test
    able to say so.

    ★Coils and R0/B0 only.  The two are not the same DOCUMENT — the preset
    carries a grid RESOLUTION and a device id, which are the page's and not
    the machine's, and the fyo document carries provenance and the absence
    markers the page has no use for.  What must agree is the machine.
    """
    dev = device.load_device(ITER_DOC)
    pre = json.loads((PRESETS / "iter.jsonld").read_text(encoding="utf-8"))

    want = {}
    for c in pre["pf_active"]["coil"]:
        el = c["element"][0]
        rect = el["geometry"]["rectangle"]
        want[c["name"]] = (rect["r"], rect["z"], rect["width"], rect["height"],
                           float(el["turns_with_sign"]))
    assert len(want) == 12, f"the preset carries {len(want)} coils"

    got = {}
    for coil in dev["pf_active"]["coil"]:
        el = coil["element"][0]
        rect = el["geometry"]["rectangle"]
        #: ★`turns_with_sign` on the ELEMENT — the DD's own spelling, and the
        #: canonical one.  It was `coil.turns` for one batch.
        got[coil["name"]] = (rect["r"], rect["z"], rect["width"],
                             rect["height"], float(el["turns_with_sign"]))
    assert set(got) == set(want), (sorted(got), sorted(want))
    for name in want:
        assert got[name] == pytest.approx(want[name], rel=0, abs=0), name

    assert dev["machine"]["r_centre"] == pytest.approx(pre["tf"]["r0"])
    #: ★★2026-09-02 的一个**已知缺口，留在明处**：装置牌改为从 fydoc 的 A-Box
    #: 按需拖回之后，拖回来的 ITER 卡片**没有 `machine.fylite:b0`**（内核仓那份
    #: committed 的有，5.3 T）。上游的 `tf` 组带着 `b_field_phi_vacuum_r`，但那是
    #: 另一个名字下的另一条路——不在这里替它换算，换算就成了这道闸自己发明的事实。
    if "fylite:b0" not in dev["machine"]:
        pytest.skip("拖回来的装置牌没有 machine.fylite:b0（上游 A-Box 不带；"
                    "内核仓那份 committed 的有，2026-09-02 随 machine_desc/ 废弃）")
    assert dev["machine"]["fylite:b0"] == pytest.approx(pre["tf"]["b0"])
