#!/usr/bin/env python3
"""把 IMAS DD 的**结构**投影成数据层读的那张扁平表。

    python tools/dd-ids-table.py                      # 用已装的 imas-data-dictionaries
    python tools/dd-ids-table.py --dd-xml IDSDef.xml  # 用一份 DD 的 IDSDef.xml
    python tools/dd-ids-table.py --version 4.1.1 --ids equilibrium core_profiles

★★**它是什么。** `rust/fylite_runtime/` 要把 fyo 文档写成 **imas-python 能原样读回**的
netCDF 与 HDF5。那两种布局都不是「把树平铺」那么简单：netCDF 的**维度名**由 DD 的
坐标声明推出来（`imas/backends/netcdf/nc_metadata.py`——`1...N` 生一个以路径命名的
维、`../grid/dim1` 共用被引用量的维、`time` 在齐次时间下并成根 `time`），读回时
逐变量核对，维名对不上就拒收。所以数据层需要 DD 的**结构**：每条路径的种类、维数、
单位、坐标声明。这张表就是那些，不多一个字。

★★**为什么从 DD 的 XML 生成而不从 fyo 的 schema。** fyo 是本仓的本体，但 fyo 的
`dd_coordinate*` 注记是导入时的 XSD 相对写法（`../grid/dim1`），而且**没有**带上
`alternative_coordinate1` 与 `coordinate*_same_as`——正是 imas-python 决定维名要用的
两样。imas-python 读的是编译后的 `IDSDef.xml`（绝对写法 `time_slice(itime)/...`）。
要与它逐字一致，就从它读的同一份东西生成。fyo 那侧的语义（类型、`fylite:` 词表）
不在这张表里，也不需要在。

★**DD 的文字一个字不抄**（fyo `CLAUDE.md`：CC BY-ND 的 `documentation` 只留指针，
不进本仓）。这里只有路径、种类、维数、单位、坐标——结构，不是文字。

## 表的格式（`rust/fylite_runtime/ids/<ids>.tsv`）

    # fylite/ids-table/1
    # dd_version 4.1.1
    # ids equilibrium
    # columns path kind ndim units coordinates same_as alternatives
    time_slice/profiles_2d/psi<TAB>F<TAB>2<TAB>Wb<TAB>time_slice(itime)/profiles_2d(i1)/grid/dim1|time_slice(itime)/profiles_2d(i1)/grid/dim2<TAB><TAB>

kind：`S` 结构 · `A` 结构数组 · `F` 浮点 · `I` 整数 · `C` 复数 · `T` 字符串。
coordinates：逐维以 `|` 分隔，原文照抄 DD（含 `1...N`、` OR `、`IDS:`）。
same_as：逐维 `coordinateN_same_as`，同样 `|` 分隔。alternatives：`alternative_coordinate1`
的 `;` 表。

★`_error_upper` / `_error_lower` / `_error_index` 三种叶子**不入表**：imas-python 的
规则是它们与本体同维（`nc_metadata.py` 的 errorbar 分支），数据层按同一条规则现算，
省下三分之一的行。

同时生成 `rust/fylite_runtime/src/ids_tables.rs`：`include_str!` 全部表的一张索引。
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "rust" / "fylite_runtime" / "ids"
RS = ROOT / "rust" / "fylite_runtime" / "src" / "ids_tables.rs"
SCHEMA = "fylite/ids-table/1"

KIND = {"structure": "S", "struct_array": "A", "FLT": "F", "INT": "I", "CPX": "C", "STR": "T"}


def kind_ndim(data_type: str) -> tuple[str, int]:
    if data_type in ("structure", "struct_array"):
        return KIND[data_type], 1 if data_type == "struct_array" else 0
    base, _, dim = data_type.partition("_")
    if base not in KIND or not dim.endswith("D"):
        sys.exit(f"[dd-ids-table] unknown data_type {data_type!r}")
    return KIND[base], int(dim[:-1])


def load_xml(args) -> ET.Element:
    if args.dd_xml:
        return ET.parse(args.dd_xml).getroot()
    try:
        from imas import dd_zip
    except ImportError:
        sys.exit("[dd-ids-table] neither --dd-xml nor the imas-python package (imas.dd_zip) is available")
    return ET.fromstring(dd_zip.get_dd_xml(args.version))


def rows_of(ids: ET.Element):
    for el in ids.iter("field"):
        path = el.attrib.get("path")
        if not path:
            continue
        name = path.rsplit("/", 1)[-1]
        if name.endswith(("_error_upper", "_error_lower", "_error_index")):
            continue
        kind, ndim = kind_ndim(el.attrib["data_type"])
        coords = [el.attrib.get(f"coordinate{i}", "") for i in range(1, ndim + 1)]
        same = [el.attrib.get(f"coordinate{i}_same_as", "") for i in range(1, ndim + 1)]
        yield (path, kind, str(ndim), el.attrib.get("units", ""),
               "|".join(coords), "|".join(same) if any(same) else "",
               el.attrib.get("alternative_coordinate1", ""))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dd-xml", help="a DD IDSDef.xml (default: imas-data-dictionaries)")
    ap.add_argument("--version", default="4.1.1", help="DD version to take from imas-data-dictionaries")
    ap.add_argument("--ids", nargs="*", help="only these IDSs (default: all)")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    root = load_xml(args)
    version = (root.findtext("version") or args.version).strip()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    names = []
    total = 0
    for ids in root.findall("IDS"):
        name = ids.attrib["name"]
        if args.ids and name not in args.ids:
            continue
        rows = list(rows_of(ids))
        lines = [f"# {SCHEMA}", f"# dd_version {version}", f"# ids {name}",
                 "# columns path kind ndim units coordinates same_as alternatives"]
        lines += ["\t".join(r) for r in rows]
        text = "\n".join(lines) + "\n"
        (out / f"{name}.tsv").write_text(text)
        names.append(name)
        total += len(text)
    names.sort()
    rs = ['//! GENERATED by tools/dd-ids-table.py — do not edit.',
          '//!',
          '//! The IMAS DD structure tables (`ids/<ids>.tsv`) the IMAS layouts are',
          '//! written from: one `include_str!` per IDS, keyed by IDS name.',
          f'//! DD version {version}; {len(names)} IDSs.',
          '',
          f'pub const DD_VERSION: &str = "{version}";',
          '',
          'pub const TABLES: &[(&str, &str)] = &[']
    rs += [f'    ("{n}", include_str!("../ids/{n}.tsv")),' for n in names]
    rs += ['];', '']
    RS.write_text("\n".join(rs))
    print(f"[dd-ids-table] {len(names)} IDSs, {total/1e6:.2f} MB of tables -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
