// Generate `app/pages/page_*.html` — the four function pages under the v2
// shell (`FYL-DESIGN-11` V-11 / V-12, `FYL-DESIGN-10` P-25 / P-26 / P-27).
//
//     node tools/make-page-v2.mjs           # write
//     node tools/make-page-v2.mjs --check   # fail if what is on disk differs
//
// ★WHY A TRANSFORM AND NOT FOUR NEW FILES.
//
// The four originals are 397–1087 lines of markup wired to three controllers
// totalling some 14 000 lines.  A hand-written second copy would be
// functionally complete on the day it was written and wrong by the end of the
// week: every id, every `data-i18n` key, every `data-part` and every panel a
// controller reaches for would have to be kept in step by hand, against no
// gate.  That is the failure this repository names most often.
//
// So the original page IS the source.  What differs between the two versions
// is the SHELL and nothing else — which is exactly the claim `FYL-DESIGN-11`
// makes (V-15: the shell is one layer, the page body is another).  The
// transform below is therefore short, and its shortness is the evidence:
//
//   1. the `<header class="top">` strip becomes `<header class="shell">`
//   2. the page loads `shell.css` and `shell.js`
//   3. `<body>` is marked `data-fy-shell="v2"`
//
// Everything else — every panel, every control, every script — is copied
// through byte for byte.  The relocations that make the strip work
// (`.panel.toolbar` into row 2, the mode keys under the strip, the shared
// panels into a side column) happen at RUNTIME in `shell.js`, by moving the
// live nodes, so no id and no listener is ever re-created.
//
// ★The originals stay.  They are the source of these files and the control
// against which the new ones are measured; when the v2 shell is adopted, this
// generator and the originals retire together.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const PAGES = join(HERE, '..', 'app', 'pages');

/** The four function pages, and the status line each toolbar starts with. */
const IDS = ['pulse_design', 'model', 'analysis', 'data', 'report'];

const BANNER = `<!-- GENERATED by tools/make-page-v2.mjs from pages/%SRC% — do not edit.
     The v2 page shell: one sticky two-row strip shared by the four function
     pages (FYL-DESIGN-11 V-11 / V-12), the mode keys in the body rather than
     on the strip (FYL-DESIGN-09 D-23), the intro folded to one line and the
     shared controls beside the bars so the 16:9 first screen carries an
     output (FYL-DESIGN-10 P-26).
     ★The BODY of this file is the original's, byte for byte.  Only the strip
     differs; everything that makes the page work is relocated at runtime by
     assets/shell.js, which moves the live nodes rather than rebuilding them. -->
`;

/**
 * The strip, as static markup.
 *
 * ★Static, not built by script.  `theme.js` binds `#theme-toggle` on
 * `DOMContentLoaded` and `site.js` fills `[data-line-h1]` in the same tick; a
 * strip assembled by JavaScript would have to win a race against both.  The
 * two rows are empty of controls on purpose — `shell.js` moves the page's own
 * into them once they exist.
 */
const shell = (id, titles) => `<header class="shell" role="banner">
  <div class="shell-r1">
    <a class="brand" href="../index.html"><img src="../assets/fy_mark.svg" alt="" width="28" height="28"></a>
    ${titles}
    <p class="warn-internal" role="note"><span data-i18n="chrome.internal_only">仅限内部测试，请勿公开传播！</span></p>
    <!-- the four page icons are injected here by site.js installNav() -->
    <nav>
      <button id="theme-toggle" class="iconbtn" type="button"></button>
    </nav>
  </div>
  <!-- row 2: ④ input · ⑤ run state · ⑥ exit.  Filled by shell.js with the
       page's OWN controls, moved here from the body. -->
  <div class="shell-r2" id="${id}-shell-work">
    <div class="shell-in"></div>
    <div class="shell-state"></div>
    <div class="shell-exit"></div>
  </div>
  <!-- the progress line, welded to the strip's bottom edge: the run key is
       down in a function bar, and this is the only place the two are visible
       at the same time (V-11) -->
  <div class="shell-prog"></div>
</header>`;

/**
 * Replace the one `<header class="top">…</header>` block.
 *
 * ★The page's own `.titles` block is carried across verbatim rather than
 * re-declared.  The three scenario pages leave it to `site.js render()`
 * (`data-line-h1`), but the data page is a TOOL page — `render()` never runs
 * for it and its heading is its own `data-i18n="mds.h1"`.  A hardcoded
 * `data-line-h1` here left that page with a blank title, which is how this
 * was found.
 */
function swapHeader(src, id) {
  const a = src.indexOf('<header class="top">');
  if (a < 0) throw new Error('no <header class="top"> found');
  const b = src.indexOf('</header>', a);
  if (b < 0) throw new Error('unterminated header');
  const head = src.slice(a, b);
  const t0 = head.indexOf('<div class="titles">');
  const t1 = head.indexOf('</div>', t0);
  if (t0 < 0 || t1 < 0) throw new Error('no .titles block in the header');
  const titles = head.slice(t0, t1 + '</div>'.length)
    .replace(/\n\s*/g, '\n      ').trim();
  return src.slice(0, a) + shell(id, titles) + src.slice(b + '</header>'.length);
}

function transform(src, id, srcName) {
  let out = src;

  // 1. the strip
  out = swapHeader(out, id);

  // 2. the stylesheet, right after the site's own so it can override
  const cssTag = '<link rel="stylesheet" href="../assets/site.css">';
  if (!out.includes(cssTag)) throw new Error('site.css link not found');
  out = out.replace(cssTag,
    cssTag + '\n<link rel="stylesheet" href="../assets/shell.css">');

  // 3. the script.  After `host.js`, which is the last of the chrome scripts;
  //    order does not actually matter (shell.js waits for what it moves) but
  //    keeping the chrome together is how the head stays readable.
  const jsTag = '<script src="../assets/host.js"></script>';
  if (!out.includes(jsTag)) throw new Error('host.js script not found');
  out = out.replace(jsTag, jsTag + '\n<script src="../assets/shell.js"></script>');

  // 4. the opt-in flag.  Nothing in shell.js or shell.css applies without it,
  //    which is what keeps the four originals untouched.
  const bodyTag = `<body data-page="${id}">`;
  if (!out.includes(bodyTag)) throw new Error(`body tag ${bodyTag} not found`);
  out = out.replace(bodyTag, `<body data-page="${id}" data-fy-shell="v2">`);

  // 5. the banner, immediately after the doctype
  out = out.replace(/^<!DOCTYPE html>\n/i,
    '<!DOCTYPE html>\n' + BANNER.replace('%SRC%', srcName));

  return out;
}

const check = process.argv.includes('--check');
let stale = [];
for (const id of IDS) {
  const srcPath = join(PAGES, `${id}.html`);
  const dstPath = join(PAGES, `page_${id}.html`);
  if (!existsSync(srcPath)) throw new Error(`missing source ${srcPath}`);
  const body = transform(readFileSync(srcPath, 'utf8'), id, `${id}.html`);
  if (check) {
    const old = existsSync(dstPath) ? readFileSync(dstPath, 'utf8') : null;
    const differs = old !== body;
    console.log(`  ${differs ? 'DIFFERS' : 'ok     '}  pages/page_${id}.html`);
    if (differs) stale.push(`pages/page_${id}.html`);
  } else {
    writeFileSync(dstPath, body);
    console.log(`  pages/page_${id}.html  (${(body.length / 1024).toFixed(1)} kB)`);
  }
}
if (check && stale.length) {
  console.error('\n生成物已漂移，请重跑 node tools/make-page-v2.mjs：\n  '
    + stale.join('\n  '));
  process.exit(1);
}
if (check) console.log(`${IDS.length} 个页面与生成器一致。`);
