#!/usr/bin/env python3
"""Write the footer QR code of `app/` — ONE code, pointing at the site.

    python tools/make-app-qr.py [--url https://fusion-yun.github.io/fylite]

★WHY A BUILD STEP AND NOT A SCRIPT IN THE PAGE.  The browser front end vendors
no third-party JavaScript, and a QR encoder written by hand here would be a
Reed-Solomon implementation with no oracle to check it against — exactly the
shape of thing this repository refuses elsewhere.  The codes are therefore
generated ONCE, by a library that is already trusted for the poster's code
(`qrcode`, in the shared environment), and committed as plain SVG: no runtime
dependency, no encoder of ours to be wrong.

★The URL is baked in.  A QR is a printed thing — it cannot ask where it is
being served from — so it points at the published site.  If the site moves,
re-run this with `--url` and commit the new file; `validate-site.mjs` checks
that every page carries the code, not that the code says the right thing,
because nothing in the browser can check that either.

★ONE CODE, NOT ONE PER PAGE (2026-09-01 ruling).  There used to be ten, each
encoding its own page.  A footer QR is scanned to hand the SITE to somebody —
a phone at a poster or across a meeting room — and what that person wants is
the entrance, not the sub-page the scanner happened to be standing in front
of.  Ten codes also meant ten artefacts to regenerate and a gate rule
("a page's QR must be its own") whose only purpose was to keep them in step
with each other.
"""

import argparse
import pathlib

import qrcode

# page id -> path under the site root.  The scenario pages and the tool page
# sit one level down, in `pages/`.
#
# ★THE THREE PROSE PAGES EXIST ONCE PER LANGUAGE and each file needs its own
# code.  A QR is scanned from a poster or a screen by someone who is not the
# reader who opened the page, so it cannot resolve the language from anything on
# the device — before the split it pointed at `index.html` and the scanner got
# whichever language their own localStorage happened to hold.  `index-en` reads
# `index.en.html`: a dot is legal in a filename but reads as an extension.

BORDER = 2  # quiet zone, in modules; 4 is the standard, 2 is what the poster used


def svg(matrix, url):
    """One <path> of module squares, sized in module units."""
    n = len(matrix)
    side = n + 2 * BORDER
    d = []
    for y, row in enumerate(matrix):
        x = 0
        while x < n:
            if not row[x]:
                x += 1
                continue
            run = 1
            while x + run < n and row[x + run]:
                run += 1
            d.append(f"M{x + BORDER} {y + BORDER}h{run}v1h-{run}z")
            x += run
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {side} {side}" '
        f'width="{side}" height="{side}" shape-rendering="crispEdges" '
        f'role="img" aria-label="QR: {url}">\n'
        f"  <!-- Generated by tools/make-app-qr.py — do not edit by hand.\n"
        f"       Payload: {url} -->\n"
        f'  <rect width="{side}" height="{side}" fill="#ffffff"/>\n'
        f'  <path fill="#000000" d="{"".join(d)}"/>\n'
        f"</svg>\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default="https://fusion-yun.github.io/fylite")
    ap.add_argument("--out", default=None, help="app/assets (default: beside this repo)")
    a = ap.parse_args()

    out = pathlib.Path(a.out) if a.out else pathlib.Path(__file__).resolve().parents[1] / "app" / "assets"

    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M,
                       border=0, box_size=1)
    qr.add_data(a.url)
    qr.make(fit=True)
    m = qr.get_matrix()
    f = out / "qr-site.svg"
    f.write_text(svg(m, a.url), encoding="utf-8")
    print(f"{f.name}: {len(m)}x{len(m)} modules  <- {a.url}")


if __name__ == "__main__":
    main()
