// The version a page SHOWS and a file RECORDS must be the version that was
// built (T-VER).
//
// ★Why this is its own gate.  Three numbers — the kernel's release, the front
// end's, and the ABI — are written down in exactly one place,
// `rust/wasm/abi.json`, GENERATED by `rust/build.sh` from `Cargo.toml`,
// `c_api.rs` and `VERSION`.  From there they reach a reader by two different
// routes: a scenario page loads the generated `assets/version.js` and
// `site.js` renders the chip; a prose page has it baked in by
// `tools/make-app-pages.mjs`.  Two routes from one source is exactly the
// shape that drifts — and a footer that is one release behind the binary
// beside it is worse than a footer with no version at all, because it is
// believed.
//
// The oracle here never goes through either emitter: every expected value is
// read straight out of `abi.json`, and the ABI is additionally read back from
// the running kernel itself (`fylite_rs_abi_version`), so a page agreeing
// with a stale `abi.json` still fails.
//
//   node app/tests/validate-version.mjs [--playwright DIR] [--chrome BIN] [--url BASE]

import { readFileSync } from 'node:fs';
import vm from 'node:vm';

import { browser, flag } from './_browser.mjs';

const HERE = new URL('.', import.meta.url).pathname;
const BASE = flag('url') || 'http://127.0.0.1:8767/app/';
const VER = JSON.parse(readFileSync(HERE + '../assets/abi.json', 'utf8'));

let bad = 0;
const ok = (what, cond, note) => {
  console.log(`  ${cond ? 'ok  ' : 'FAIL'}  ${what}${note ? '  — ' + note : ''}`);
  if (!cond) bad += 1;
};

console.log(`〔零〕生成的那份就是三个数的唯一出处`);
ok('abi.json 三样俱全',
   Number.isInteger(VER.abi_version) && !!VER.kernel_version && !!VER.app_version,
   `ABI ${VER.abi_version} · kernel ${VER.kernel_version} · app ${VER.app_version}`);
//: non-degeneracy: two of the three being the same string would let a chip
//: that prints one of them twice pass every check below.
ok('内核与前端的版本号不是同一个字符串（否则下面的比对形同虚设）',
   VER.kernel_version !== VER.app_version,
   `${VER.kernel_version} vs ${VER.app_version}`);

console.log(`\n〔一〕version.js 就是 abi.json（生成的两份不许各说各的）`);
{
  const sandbox = { self: {} };
  vm.createContext(sandbox);
  vm.runInContext(readFileSync(HERE + '../assets/version.js', 'utf8'), sandbox);
  const V = sandbox.self.FyVersion;
  ok('version.js 定义了 FyVersion', !!V);
  ok('kernel 相同', V && V.kernel === VER.kernel_version, V && V.kernel);
  ok('app 相同', V && V.app === VER.app_version, V && V.app);
  ok('abi 相同', V && V.abi === VER.abi_version, V && String(V.abi));
}

console.log(`\n〔二〕导出的文档记下这两个版本`);
{
  //: `session.js` is an IIFE over `root`; give it a root carrying the same
  //: `FyVersion` a page would have, and ask it for an envelope.
  const sandbox = { self: {} };
  vm.createContext(sandbox);
  vm.runInContext(readFileSync(HERE + '../assets/version.js', 'utf8'), sandbox);
  vm.runInContext(readFileSync(HERE + '../assets/fyo-interface.js', 'utf8'), sandbox);
  vm.runInContext(readFileSync(HERE + '../assets/fyo.js', 'utf8'), sandbox);
  vm.runInContext(readFileSync(HERE + '../assets/session.js', 'utf8'), sandbox);
  const doc = sandbox.self.FySession.envelope('design', { a: 1 },
                                              { abi: VER.abi_version, sha256: 'deadbeef' });
  ok('文档记下内核版本', doc['fylite:kernel_version'] === VER.kernel_version,
     doc['fylite:kernel_version']);
  ok('文档记下前端版本', doc['fylite:app_version'] === VER.app_version,
     doc['fylite:app_version']);
  ok('握手那一段仍在（sha256 说的是哪一个二进制，版本说的是哪一次发布）',
     !!doc['fylite:kernel'] && doc['fylite:kernel'].sha256 === 'deadbeef');

  //: ★a page that never loaded version.js must write null, not a guess.
  const bare = { self: {} };
  vm.createContext(bare);
  vm.runInContext(readFileSync(HERE + '../assets/fyo-interface.js', 'utf8'), bare);
  vm.runInContext(readFileSync(HERE + '../assets/fyo.js', 'utf8'), bare);
  vm.runInContext(readFileSync(HERE + '../assets/session.js', 'utf8'), bare);
  const d2 = bare.self.FySession.envelope('design', {}, null);
  ok('没有加载 version.js 的页面写 null，而不是猜一个',
     d2['fylite:kernel_version'] === null && d2['fylite:app_version'] === null);
}

console.log(`\n〔三〕页面上真的画出来了，而且跟着语言走`);
const br = await browser();
const errs = [];
const PAGES = ['pages/pulse_design.html', 'pages/model.html',
               'pages/analysis.html', 'pages/data.html'];
for (const path of PAGES) {
  //: ★a FRESH context per page.  The language is remembered in
  //: `localStorage`, so reusing one context means the second page opens in
  //: whatever the first was switched to — and the repaint check below then
  //: compares English with English and passes on a chip that never moved.
  const pctx = await br.newContext({ locale: 'zh-CN',
                                     viewport: { width: 1400, height: 900 } });
  const page = await pctx.newPage();
  page.on('pageerror', (e) => errs.push(`${path}: ${String(e).slice(0, 120)}`));
  await page.goto(BASE + path, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('footer .ver', { timeout: 30000 }).catch(() => {});
  const txt = await page.evaluate(() => {
    const e = document.querySelector('footer .ver');
    return e ? e.textContent : null;
  });
  const has = txt && [VER.kernel_version, String(VER.abi_version), VER.app_version]
    .every((w) => txt.includes(w));
  ok(`${path} 的页脚带着这三个数`, !!has, txt);

  //: the chip is rendered through `t()` with placeholders, so a language
  //: change must repaint it — an early version subscribed nothing and froze
  //: in whichever language happened to load first.
  await page.evaluate(() => window.FyI18n && window.FyI18n.use('en'));
  const en = await page.evaluate(() => {
    const e = document.querySelector('footer .ver');
    return e ? e.textContent : null;
  });
  ok(`${path} 换语言之后版本牌跟着换`,
     !!en && en !== txt && en.includes(VER.kernel_version), en);
  await page.close();
  await pctx.close();
}
ok('没有 pageerror', errs.length === 0, errs[0] || '');

console.log(`\n〔四〕页面印的 ABI 就是随它一起发的那个二进制自报的 ABI`);
{
  //: ★the oracle here is the SHIPPED WASM, instantiated directly — no page,
  //: no `abi.json`.  `abi.json` and the pages could agree with each other and
  //: both be one release behind `app/assets/fylite_rs.wasm`; this is the only
  //: check that catches that, and it is the exact failure mode the Python
  //: side already has a test for (a committed `.so` speaking an older ABI
  //: than the `_abi.py` generated beside it).
  const bytes = readFileSync(HERE + '../assets/fylite_rs.wasm');
  const mod = await WebAssembly.instantiate(bytes, {
    env: { emscripten_notify_memory_growth: () => {} },
    wasi_snapshot_preview1: new Proxy({}, { get: () => () => 0 }),
  }).catch((e) => ({ err: e }));
  if (mod.err) {
    ok('随页面发的 fylite_rs.wasm 能实例化', false, String(mod.err).slice(0, 120));
  } else {
    const abi = mod.instance.exports.fylite_rs_abi_version();
    ok('随页面发的 fylite_rs.wasm 自报的 ABI 就是页脚印的那个',
       abi === VER.abi_version, `wasm ${abi} · 页脚 ${VER.abi_version}`);

    //: ★T-A18 的关闭判据，钉在发的二进制上：`spitzer_eta` 自 v111 起是
    //: 平行支，`spitzer_eta_perp` 是它 v110 及以前的值（NRL 垂直系数原
    //: 样），两者之比逐点恒为 0.51。放在这一闸是因为这里已经把随页面发
    //: 的 wasm 实例化了——比的就是读者拿到的那份二进制，不是源码。
    const E = mod.instance.exports;
    const te = [50, 300, 2000, 15000], z = [1, 1.5, 2, 4],
          ln = [10, 14, 17, 20], n = te.length;
    const buf = (v) => {
      const p = Number(E.fylite_rs_alloc(BigInt(8 * n)));
      new Float64Array(E.memory.buffer, p, n).set(v);
      return p;
    };
    const pt = buf(te), pz = buf(z), pl = buf(ln),
          o1 = buf(new Array(n).fill(0)), o2 = buf(new Array(n).fill(0));
    const r1 = E.fylite_rs_spitzer_eta(pt, pz, pl, BigInt(n), o1);
    const r2 = E.fylite_rs_spitzer_eta_perp(pt, pz, pl, BigInt(n), o2);
    const par = Array.from(new Float64Array(E.memory.buffer, o1, n));
    const perp = Array.from(new Float64Array(E.memory.buffer, o2, n));
    ok('spitzer_eta 与 _perp 两个入口都答得出', r1 === 0 && r2 === 0,
       `rc ${r1}/${r2}`);
    const worst = Math.max(...par.map((v, i) =>
      Math.abs(v / perp[i] - 0.51)));
    ok('η_par/η_perp 逐点恒为 0.51（T-A18 的订正是一个可查的关系）',
       worst < 1e-15, `最大偏离 ${worst.toExponential(1)}`);
    //: 垂直支就是 NRL 公式原样——0.51 没有被塞进它那一边再除回来
    const nrl = te.map((t, i) => 1.03e-4 * z[i] * ln[i] / Math.pow(t, 1.5));
    const wp = Math.max(...perp.map((v, i) => Math.abs(v / nrl[i] - 1)));
    ok('η_perp 是 NRL 系数原样', wp < 1e-12, `相对 ${wp.toExponential(1)}`);
    [pt, pz, pl, o1, o2].forEach((p) => E.fylite_rs_free(p, BigInt(8 * n)));
  }
}

await br.close();
console.log(`\n判定：版本自报${bad ? `不通过（${bad} 项）` : '通过'}`);
process.exit(bad ? 1 : 0);
