// Gate for the SITE's shape: four scenarios, one page each, and the
// navigation between them.
//
// ★This replaces `validate-lines.mjs`, and what it dropped is the point.
// That gate parsed a requirement-coverage table out of a design document and
// compared it row by row with a table in `lines.js`.  It was a real check of
// a real invariant — while the invariant existed.  The "lines" model is
// withdrawn (a page is a scenario now, free to gain a stage or lose one), and
// with it the rule 「一页都不退，一页都不并」, so a gate that made two files
// agree about requirement rows was checking bookkeeping, not the app.
//
// What it still checks is what a reader can get wrong today:
//
//   1. THE SITE IS ITS PAGES.  Five files, one per scenario plus the
//      entrance, and every scenario's stages have a section to live in.
//   2. NO SECTION IS IN TWO PLACES, and every element id inside one carries
//      its stage's prefix.  Sixty ids collided across the former method
//      pages; an unprefixed one is not a visible break — the first stage's
//      control answers for the second stage's slider.
//   3. EVERY PAGE IS REACHABLE AND DECLARES ITSELF: it loads `site.js`, it
//      names a `data-page` the module knows, and every hand-written link
//      resolves.
//   4. EVERY MESSAGE THE PAGES ASK FOR EXISTS IN BOTH LANGUAGES, and no
//      prose is left in the shared catalogues that nothing shows.
//
//   node tests/app/validate-site.mjs

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import vm from 'node:vm';

const HERE = new URL('.', import.meta.url).pathname;
const APP = HERE + '../';

//: ★the one place the three numbers are written down, GENERATED by
//: `rust/build.sh`.  Read here rather than re-declared so this gate cannot
//: drift from the emitters it judges.
const VER = JSON.parse(readFileSync(HERE + '../assets/abi.json', 'utf8'));
const SITE = APP + 'assets/';

let bad = 0;
const fail = (m) => { console.log('  FAIL ' + m); bad++; };
const ok = (m) => console.log('  ok   ' + m);

// --- load the catalogues, keeping the languages apart ----------------------
//
// FyI18n.t falls back to zh for a missing key, so asking it whether a key
// exists in en cannot answer.  The register calls are intercepted instead.

globalThis.self = globalThis;
vm.runInThisContext(readFileSync(SITE + 'i18n.js', 'utf8'), { filename: 'i18n.js' });

const CAT = { zh: new Set(), en: new Set() };
const realRegister = globalThis.FyI18n.register;
globalThis.FyI18n.register = (code, table) => {
  Object.keys(table).forEach((k) => CAT[code] && CAT[code].add(k));
  return realRegister(code, table);
};
// Every catalogue, not only the line ones: the static `data-i18n` sweep below
// covers all fifteen pages, and a nav key missing from one tool page's
// catalogue has been the actual failure twice before.
const CATFILES = readdirSync(SITE).filter((f) => /^lang-.*\.js$/.test(f)).sort();
for (const f of CATFILES)
  vm.runInThisContext(readFileSync(SITE + f, 'utf8'), { filename: f });

// --- a DOM small enough to be honest --------------------------------------
//
// The point is not to render; it is to run the REAL renderer and record which
// message keys it asks for.  Recomputing the key list by hand here would
// check this script against itself.

const wanted = new Set();

class El {
  constructor(tag) { this.tag = tag; this.children = []; this.attrs = {}; }
  setAttribute(k, v) {
    this.attrs[k] = v;
    if (k === 'data-i18n') wanted.add(v);
  }
  getAttribute(k) { return this.attrs[k]; }
  appendChild(c) { this.children.push(c); return c; }
  insertBefore(c) { this.children.unshift(c); return c; }
  remove() {}
  addEventListener() {}
  querySelectorAll() { return []; }
  get firstChild() { return this.children[0] || null; }
}

const main = new El('main');
const body = new El('body');
// The header's title and subtitle are marked in the markup and given their
// key by the renderer, so the stub has to hand them over or those two keys
// would never be recorded and a missing translation would slip through.
const nodes = {};
const slots = { '[data-line-h1]': [new El('h1')], '[data-line-sub]': [new El('span')] };
globalThis.document = {
  readyState: 'complete',
  body,
  documentElement: {},
  createElement: (t) => new El(t),
  createTextNode: (t) => ({ text: t }),
  querySelector: (s) => (s === 'main.doc' ? main : null),
  querySelectorAll: (s) => slots[s] || [],
  // the tab bar and one section per tool, so `tabs()` runs for real.
  //: a MERGED scenario has no tab bar and shows every section at once —
  //: `showAll()` runs here instead, which needs the same section nodes
  //: `line-doc` too: the scenario's own lead and scope are appended there,
  //: and a stub that returned null for it would report their keys as prose
  //: nothing shows
  getElementById: (id) => (id === 'line-doc' || /^tool-/.test(id)
    ? (nodes[id] || (nodes[id] = new El('div'))) : null),
  addEventListener: () => {},
};

globalThis.location = { hash: '' };
globalThis.history = { replaceState: () => {} };
globalThis.addEventListener = () => {};
globalThis.dispatchEvent = () => {};
globalThis.Event = class { constructor(t) { this.type = t; } };

const realT = globalThis.FyI18n.t;
globalThis.FyI18n.t = (k, p) => { wanted.add(k); return realT(k, p); };
globalThis.FyI18n.applyDom = () => {};

vm.runInThisContext(readFileSync(SITE + 'site.js', 'utf8'), { filename: 'site.js' });
const { SCENARIOS, TOOLS } = globalThis.FySite;

// --- 3. nothing unreachable, nothing dangling -----------------------------

// Paths here are site-root-relative, the same form `lines.js` writes them in:
// the entrance sits at the root, the scenario pages and the tool page one
// level down in `pages/`.
const htmls = [
  ...readdirSync(APP).filter((f) => f.endsWith('.html')),
  ...readdirSync(APP + 'pages/').filter((f) => f.endsWith('.html'))
      .map((f) => 'pages/' + f),
];
//: ★THE SITE IS TWO SHAPES OF PAGE, and nearly every check below has to know
//: which one it is looking at.
//:
//: A SCENARIO page is an instrument: it loads `site.js`, its nav and its footer
//: are injected, and it switches language in place.
//:
//: A PROSE page — the entrance, the capability page, the credits — carries no
//: part and no compute.  It is GENERATED, once per language, by
//: `tools/make-app-pages.mjs`: the text is in the markup, there is no i18n
//: runtime and no `site.js`, and the language is in the FILE NAME.  That is why
//: there are six of them for three pages, and why `index.en.html` is a page and
//: not a stray file.
//:
//: A TOOL page is the third shape, added with `pages/data.html`.  It is
//: DYNAMIC like a scenario — one file, `site.js` injecting its nav and footer,
//: the language switched in place — but it is NOT a scenario: it computes
//: nothing, so it has no part, no toolbar host and no controller registering
//: parts, and the scenario checks below must not be run against it.
//: ★It sits in `pages/` BESIDE the scenario pages — it used to sit at the site
//: root, and the assumption that it did was written into the `up` rule below.
//: A tool page is one directory down like a scenario now, so it prefixes
//: `../` exactly like one; what still sets it apart from a prose page is that
//: it exists ONCE, so its home link takes no language suffix.
const FLATIDS = ['index', 'features', 'credits'];
const LANGS = ['zh', 'en'];
const flatFile = (id, lang) => (lang === 'zh' ? `${id}.html` : `${id}.${lang}.html`);
const FLAT = new Set(FLATIDS.flatMap((id) => LANGS.map((l) => flatFile(id, l))));
const TOOLHREFS = new Set(TOOLS.map((P) => P.href));
//: ★THE V2 SHELL COPIES.  `pages/page_<id>.html` is the same page under the
//: shared two-row strip (`FYL-DESIGN-11` V-11 / V-12), GENERATED from
//: `pages/<id>.html` by `tools/make-page-v2.mjs`.  They are listed here rather
//: than tolerated by a wildcard: an unexpected file in `pages/` is exactly the
//: shape this file exists to catch, and "anything starting with page_" would
//: wave through a fifth one nobody decided to add.
const V2 = new Set([...SCENARIOS.map((S) => S.href), ...TOOLHREFS]
  .map((h) => h.replace('pages/', 'pages/page_')));
const isV2 = (f) => V2.has(f);
const EXPECTED = new Set([...FLAT, ...SCENARIOS.map((S) => S.href), ...TOOLHREFS,
                          ...V2]);
const isFlat = (f) => FLAT.has(f);
/** `index.en.html` -> `index`; `pages/design.html` -> `design`;
 *  `pages/page_model.html` -> `model` (the v2 copy IS that page) */
const idOf = (f) => f.replace('pages/', '').replace(/^page_/, '')
  .replace(/(\.[a-z]{2})?\.html$/, '');
/** the language a file is written in — a scenario page has all of them */
const langOf = (f) => (/\.en\.html$/.test(f) ? 'en' : 'zh');

// The site is the entrance, one page per scenario, and the credits.
// A stray `<tool>.html` means a method page came back — that is the shape the
// merge removed, and it would take its element ids out of the tool prefix with
// it.
for (const f of htmls)
  if (!EXPECTED.has(f)) fail(`${f} is neither a scenario nor a generated prose page`);
for (const f of EXPECTED)
  if (!existsSync(APP + f)) fail(`${f} is missing`);
if (htmls.length === EXPECTED.size)
  ok(`the site is ${htmls.length} files: ${FLATIDS.length} prose pages x ${LANGS.length}`
     + ` languages, ${SCENARIOS.length} scenarios and ${TOOLS.length}`
     + ` tool page${TOOLS.length === 1 ? '' : 's'}, plus ${V2.size} v2-shell copies`);
else fail(`the site has ${htmls.length} html files, expected ${EXPECTED.size}`);

//: ★every page must reach every OTHER prose page, IN ITS OWN LANGUAGE.  A
//: licence nobody can get to is a licence nobody read — and an English page
//: whose footer links to the Chinese credits is one a reader cannot read.
//: A scenario page's footer is injected, so the check there is that it loads
//: the module which injects it (below); a prose page carries the links.
for (const f of htmls.filter(isFlat)) {
  const src = readFileSync(APP + f, 'utf8');
  const lang = langOf(f);
  for (const id of FLATIDS) {
    if (idOf(f) === id) continue;
    if (!src.includes(`href="${flatFile(id, lang)}"`))
      fail(`${f} has no ${lang} link to ${id}`);
  }
  //: and to its own counterpart in the other language, which is the ONLY way
  //: to reach the other language at all — there is no redirect at the entrance
  const other = LANGS.find((l) => l !== lang);
  if (!src.includes(`href="${flatFile(idOf(f), other)}"`))
    fail(`${f} has no link to its ${other} counterpart`);
  if (!src.includes(`hreflang="${other}"`))
    fail(`${f} declares no \`hreflang\` alternate — the pair is not machine-readable`);
  //: ★the page stamps the language it is written in.  Without it, a reader who
  //: opens the Chinese entrance in an English-locale browser and clicks through
  //: to a scenario gets an English instrument page.
  if (!src.includes(`localStorage.setItem('fylite-lang','${lang}')`))
    fail(`${f} does not stamp its own language`);
  const declared = (src.match(/<html lang="([^"]+)"/) || [])[1];
  const want = lang === 'zh' ? 'zh-CN' : lang;
  if (declared !== want) fail(`${f} declares <html lang="${declared}">, expected "${want}"`);
}

//: ★the mark is in every header, and it is a LINK to the entrance.  ★It is the
//: square `Fy` mark ALONE, not the 240x100 wordmark and not a mark with the
//: product's name beside it: the wordmark's 7 px strapline was a smear in a
//: 30 px strip, and a name beside the mark said `fylite` twice in one strip on
//: the one page whose heading already said it.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  //: a tool page sits one directory down like a scenario, so its links carry
  //: `../` — but it switches language in place, so its home link takes no
  //: language suffix.  Only a prose page is at the site root.
  const up = isFlat(f) ? '' : '../';
  const home = isFlat(f) ? flatFile('index', langOf(f)) : `${up}index.html`;
  if (!src.includes(`<a class="brand" href="${home}"><img src="`
                    + `${up}assets/fy_mark.svg"`))
    fail(`${f} does not carry the mark, linking home in its own language`);
  //: and the same mark is the tab icon — a page that asks for `/favicon.ico`
  //: spends every visit on a 404 that browser gates count as a page error
  if (!/<link rel="icon" href="(\.\.\/)?assets\/fy_mark\.svg">/.test(src))
    fail(`${f} does not carry the mark as its tab icon`);
}

//: ★THE TWO SWITCHES ARE ICONS, and an icon button with no accessible name is
//: announced by a screen reader as "button".  Neither carries text in the
//: markup any more, so what can be checked here is that both exist, that
//: neither has had a text label put back on it — and WHERE each one is.
//:
//: ★THEY ARE NOT IN THE SAME PLACE, and that is the point of checking.  The
//: theme is flipped against the light in the room and belongs in the header
//: strip with the page's own controls; the language is picked once and never
//: again, so it sits in the footer with the site's other pages — the controls
//: that change WHICH text you are reading.  Put back together they read as one
//: cluster of two settings, which is the arrangement this replaced.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  //: ★either strip.  The v2 pages carry `header.shell`; everything asserted
  //: about the header below is asserted about whichever one the file has.
  const header = (src.match(/<header class="(?:top|shell)"[^>]*>[\s\S]*?<\/header>/)
                  || [''])[0];
  const footer = (src.match(/<footer>[\s\S]*?<\/footer>/) || [''])[0];

  const th = src.match(/<button id="theme-toggle"([^>]*)>([^<]*)<\/button>/);
  if (!th) fail(`${f} has no #theme-toggle`);
  else {
    if (!/class="iconbtn"/.test(th[1])) fail(`${f}: #theme-toggle is not an .iconbtn`);
    if (th[2].trim()) fail(`${f}: #theme-toggle carries the text "${th[2].trim()}"`);
    if (!header.includes(th[0])) fail(`${f}: #theme-toggle is not in the header`);
  }

  //: ★the language switch is a BUTTON on a scenario page (it re-renders in
  //: place) and a LINK on a generated one (there is another file).  Both show
  //: the flag of the language being READ — the control's state — and both say
  //: what pressing does in WORDS, as an action, in the language of the page:
  //: a flag alone is as easily read as "this is Chinese" as "press for
  //: Chinese", and the accessible name is where that ambiguity gets settled.
  //: ★The flag must be the page's OWN language and `hreflang` the OTHER: those
  //: two disagreeing is the bug this checks for, because each half looks right
  //: on its own.
  if (isFlat(f)) {
    const a_ = footer.match(/<a class="iconbtn"([^>]*)>/);
    if (!a_) { fail(`${f}: the footer carries no language link`); continue; }
    const lang = langOf(f);
    const other = LANGS.find((l) => l !== lang);
    const NAME = { zh: '中文', en: 'English' };
    const SWITCH = { zh: `切换到 ${NAME[other]}`, en: `Switch to ${NAME[other]}` };
    for (const attr of [`hreflang="${other}"`,
                        `title="${SWITCH[lang]}"`, `aria-label="${SWITCH[lang]}"`])
      if (!a_[1].includes(attr)) fail(`${f}: the language link lacks ${attr}`);
    if (!footer.includes(`assets/flag-${lang}.svg`))
      fail(`${f}: the language link shows a flag that is not this page's language`);
  } else if (!/assets\/site\.js/.test(src)) {
    fail(`${f}: nothing injects the language switch`);
  }

  //: ★WHICH BUILD, on every page, from both emitters.  One spec, two ways of
  //: getting there: a generated page has the chip baked in by
  //: `tools/make-app-pages.mjs`, a scenario page gets it from `site.js` and
  //: therefore has to LOAD the generated `assets/version.js` — a page that
  //: forgets the script shows no version at all, silently, which is exactly
  //: the failure this catches.  ★The numbers are checked against
  //: `rust/wasm/abi.json`, the file `rust/build.sh` generates them from, so a
  //: page regenerated before a kernel build (or not regenerated after one)
  //: fails here rather than shipping a version that is quietly one release
  //: behind the binary beside it.
  if (isFlat(f)) {
    const chip = footer.match(/<span class="ver"[^>]*>([^<]*)<\/span>/);
    if (!chip) fail(`${f}: the footer carries no version`);
    else {
      for (const want of [VER.kernel_version, String(VER.abi_version),
                          VER.app_version])
        if (!chip[1].includes(want))
          fail(`${f}: the footer's version omits ${want} — got "${chip[1]}"`);
    }
  } else if (!/assets\/version\.js/.test(src)) {
    fail(`${f}: does not load assets/version.js, so its footer has no version`);
  }
}

//: ★EVERY FILE A PAGE ASKS FOR EXISTS.  A page that references an asset which
//: is not there does not fail loudly — the browser logs a 404 and the page
//: carries on with a global that was never set, which is how a deleted preset
//: script cost an afternoon.  Stylesheets and scripts only: `.wasm` and the
//: device documents are fetched by name from code, and are checked where they
//: are named.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  const dir = f.includes('/') ? f.replace(/[^/]*$/, '') : '';
  for (const m of src.matchAll(/<(?:script src|link[^>]*href)="([^":]+)"/g)) {
    const ref = m[1];
    if (/^(?:https?:)?\/\//.test(ref)) continue;          // off-site
    const path = new URL(ref, 'file:///' + APP + dir).pathname.slice(1);
    if (!existsSync(path)) fail(`${f} loads ${ref}, which does not exist`);
  }
}

//: ★THE HANDOFF between scenarios: a page that offers to hand its result on,
//: or to take one, must load the module that carries it.  The two ends are in
//: different files and neither notices the other missing — the button would
//: simply throw on the first click, in the one place a reader is asking for
//: something to work.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  const gives = /id="[a-z_]+-handoff" class="ghost"/.test(src);
  const takes = /id="model-handoff"/.test(src);
  const loads = /assets\/handoff\.js/.test(src);
  if ((gives || takes) && !loads)
    fail(`${f} carries a handoff control but does not load assets/handoff.js`);
  if (loads && !(gives || takes))
    fail(`${f} loads assets/handoff.js and has nothing to hand over or take`);
}

//: ★THE FOOTER BAND HAS ONE SPECIFICATION AND TWO EMITTERS: `installFoot()` in
//: `site.js` injects it on a scenario page, `tools/make-app-pages.mjs` writes it
//: out on a generated one.  Two emitters reading one table is fine; what is not
//: is what this replaced — six hand-written copies that had drifted into three
//: different link sets for no reason anyone had decided.
//:
//: So a scenario page must carry an EMPTY footer (anything in it would be
//: overwritten, and a reader of the file would believe it), and a prose page
//: must carry the whole band.  Both must name a QR that exists and is their own.
//: What the code SAYS cannot be checked here or in the browser — it is baked
//: against the published url by `tools/make-app-qr.py`.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  const foot = (src.match(/<footer>[\s\S]*?<\/footer>/) || [''])[0];
  if (!foot) { fail(`${f} has no footer`); continue; }
  if (!isFlat(f)) {
    if (foot !== '<footer></footer>')
      fail(`${f}: a scenario footer is injected — its markup must be empty`);
    if (!/assets\/site\.js/.test(src))
      fail(`${f}: nothing loads site.js, so nothing injects the footer`);
    continue;
  }
  if (!foot.includes('<span class="copy">'))
    fail(`${f}: the footer does not carry the copyright line`);
  //: ★ONE code for the whole site (2026-09-01 ruling).  There used to be ten,
  //: one per page, and a rule here that each page must show its own; a footer
  //: QR is scanned to hand somebody the SITE, so what it should carry is the
  //: entrance, not whichever sub-page the scanner was pointed at.
  const qr = foot.match(/<img src="assets\/(qr-[a-z_-]+\.svg)"/);
  if (!qr) { fail(`${f}: the footer carries no QR`); continue; }
  if (qr[1] !== 'qr-site.svg')
    fail(`${f} shows ${qr[1]} — every page carries the one site code (qr-site.svg)`);
  if (!existsSync(SITE + qr[1])) fail(`${f}: ${qr[1]} does not exist`);
}
if (!existsSync(SITE + 'qr-site.svg')) fail('assets/qr-site.svg does not exist');
//: ★and there must be no others left behind: a stale per-page code is a live
//: link to a page that may have moved, and nothing renders it so nobody looks.
for (const f of readdirSync(SITE))
  if (/^qr-.*\.svg$/.test(f) && f !== 'qr-site.svg')
    fail(`assets/${f} is a leftover per-page QR — only qr-site.svg remains`);

//: ★every page must load `host.js`: it is what tells the page whether it is
//: the website or the desktop viewer, and the QR above is hidden on the
//: latter by a CSS rule that has nothing to read without it.
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  //: ★the SCRIPT TAG, not the string.  `/assets\/host\.js/` also matches the
  //: comment that sits above the tag explaining it, so a page that had lost
  //: the tag but kept the comment passed — measured, not hypothesised.
  if (!/<script[^>]+src="[^"]*assets\/host\.js"/.test(src))
    fail(`${f}: does not load assets/host.js, so data-fy-host is never set`);
}

// The parts a page is assembled from: one block each, and one controller
// each, loaded in the order they run.  ★A part is NOT a page and NOT a stage
// — it has no toolbar, no run button and no worker of its own; the page owns
// those.  What this checks is the only thing that can silently go wrong: a
// block with no controller (dead markup) or a controller with no block (a
// script that will throw on its first `$`).
const partsOf = {};
for (const S of SCENARIOS) {
  if (!existsSync(APP + S.href)) { fail(`scenario ${S.id} -> ${S.href} does not exist`); continue; }
  const own = readFileSync(APP + S.href, 'utf8');
  const secs = [...own.matchAll(/<section class="tool" id="tool-([a-z_]+)"/g)].map((m) => m[1]);
  if (secs.length !== 1 || secs[0] !== S.id)
    fail(`${S.href} carries sections [${secs}] — a page is ONE scenario section`);
  //: ★ONE INTERFACE per scenario: one toolbar, one two-column layout.  The
  //: parts are not blocks of the page any more — their panels carry
  //: `data-part` and sit among the others in the SAME control column and the
  //: SAME figure column, which is what makes the page read as one tool
  //: instead of three stacked ones.
  const hosts = (own.match(/class="toolbar-host"/g) || []).length;
  if (hosts !== 1) fail(`${S.href} has ${hosts} toolbar hosts — the page has one`);
  const layouts = (own.match(/<div class="layout">/g) || []).length;
  if (layouts !== 1)
    fail(`${S.href} has ${layouts} layouts — one scenario is one two-column interface`);
  if (/<div class="part"/.test(own))
    fail(`${S.href} still wraps a part in a block of its own`);
  const parts = [...new Set([...own.matchAll(/data-part="([a-z_]+)"/g)].map((m) => m[1]))];
  if (!parts.length) fail(`${S.href} has no parts`);
  partsOf[S.id] = parts;

  //: ★ONE controller file per scenario, named after it, with a section per
  //: part in the order the page runs them.
  const scripts = [...own.matchAll(/<script src="\.\.\/assets\/scenario-([a-z_]+)\.js"><\/script>/g)]
    .map((m) => m[1]);
  if (String(scripts) !== String([S.id]))
    fail(`${S.href} loads controllers [${scripts}], expected [${S.id}]`);
  const ctl = existsSync(SITE + `scenario-${S.id}.js`)
    ? readFileSync(SITE + `scenario-${S.id}.js`, 'utf8') : '';
  if (!ctl) fail(`assets/scenario-${S.id}.js does not exist`);
  const reg = [...ctl.matchAll(/FyScenario\.part\('([a-z_]+)'/g)].map((m) => m[1]);
  if (String(reg) !== String(parts))
    fail(`assets/scenario-${S.id}.js registers [${reg}], the page shows [${parts}]`);
}
//: and no part appears on two pages
const all = Object.values(partsOf).flat();
if (new Set(all).size !== all.length) fail(`a part appears on more than one page: ${all}`);
if (!bad) ok(`${SCENARIOS.length} scenarios, ${all.length} parts, one interface each`);

//: ★a part of a MULTI-part page needs a name: the export menu is the union of
//: the parts' formats, and their labels are told apart by it ("会话文件 · 击穿
//: 场零").  Without the key the menu offers three entries reading `nav.xxx`.
for (const [pg, parts] of Object.entries(partsOf))
  if (parts.length > 1)
    for (const part of parts)
      for (const lang of ['zh', 'en'])
        if (!CAT[lang].has('nav.' + part))
          fail(`part ${part} of ${pg} has no \`nav.${part}\` in ${lang} — its files would be labelled by a key`);

//: ★every part must be REACHABLE from the entrance.  A page whose parts are
//: several needs a card each — the scenario card leads to the page, not to
//: the demo inside it, and a part nobody can link to is a demo nobody finds.
//: A page carrying ONE part needs nothing: its scenario card, generated from
//: the same table the navigation is built from, IS that part's card.
//:
//: ★The hand-written grid this used to check is GONE, and the reason is the
//: shape it was written for.  While a page carried three demos the grid was
//: the only door to two of them; since the site was cut back to four typical
//: scenarios it repeated the generated cards word for word — and the copy
//: kept by hand is the one that drifts.  What survives is the check that
//: matters either way: no card may point at a part its page does not carry,
//: and a multi-part page may not hide a part behind no link at all.
const home = readFileSync(APP + 'index.html', 'utf8');
const carded = [...home.matchAll(/href="pages\/([a-z_]+)\.html#part-([a-z_]+)"/g)];
for (const [, page, part] of carded) {
  if (!(partsOf[page] || []).includes(part))
    fail(`index.html has a card for ${page}#part-${part}, which that page does not carry`);
}
for (const [pg, parts] of Object.entries(partsOf))
  if (parts.length > 1)
    for (const part of parts)
      if (!carded.some((m) => m[1] === pg && m[2] === part))
        fail(`part ${part} of ${pg} shares its page and has no card on the entrance`);

//: ★the scenario section must CLOSE where it says it does.  Three part blocks
//: had lost their layout wrapper when the toolbar was lifted out of them, so a
//: stray closing tag ended them early and every figure below parsed as a
//: sibling — invisible, because controllers address elements by id, but the
//: CSS scoped to those panels stopped reaching them.
for (const S of SCENARIOS) {
  const src = readFileSync(APP + S.href, 'utf8').replace(/<!--[\s\S]*?-->/g, '');
  const i0 = src.indexOf('<section class="tool"');
  //: ★the scenario section CONTAINS sections now — one per 功能栏 — so its end
  //: is the matching `</section>`, not the first one after it.  Taking the
  //: first cut the counted region short and reported every page as unbalanced.
  let depth = 0, i1 = -1;
  for (const m of src.slice(i0).matchAll(/<section\b|<\/section>/g)) {
    depth += m[0] === '</section>' ? -1 : 1;
    if (depth === 0) { i1 = i0 + m.index; break; }
  }
  if (i1 < 0) { fail(`${S.href}: the scenario section is never closed`); continue; }
  let d = 0;
  for (const m of src.slice(i0, i1).matchAll(/<div\b|<\/div>/g)) d += m[0] === '</div>' ? -1 : 1;
  if (d !== 0)
    fail(`${S.href}: the scenario section's divs do not balance (${d})`);
  //: every bar declared in the markup has a strip built for it, and the body
  //: it folds; a bar with no `funcbar-body` would fold to nothing
  for (const m of src.slice(i0, i1).matchAll(/<section data-bar="([a-z]+)">\s*\n\s*<div class="funcbar-body">/g))
    void m;
  const declared = [...src.slice(i0, i1).matchAll(/<section data-bar="([a-z]+)"/g)].map((m) => m[1]);
  const bodies = (src.slice(i0, i1).match(/<div class="funcbar-body">/g) || []).length;
  if (declared.length !== bodies)
    fail(`${S.href}: ${declared.length} bars but ${bodies} bar bodies`);
  if (!declared.length) fail(`${S.href}: the scenario declares no 功能栏`);

  //: ★A BAR IS DECLARED TWICE — in the markup that carries its panels and in
  //: the controller that runs it — and the two must name the same set.  A
  //: section nobody registers gets a strip and a fold over panels no code
  //: drives; a registration with no section has nowhere to put its strip.
  //: The exception is the implicit bar: a scenario whose controller never
  //: says `bar` gets one named after its part.
  const ctlSrc = existsSync(SITE + `scenario-${S.id}.js`)
    ? readFileSync(SITE + `scenario-${S.id}.js`, 'utf8') : '';
  const registered = [...ctlSrc.matchAll(/\.bar\('([a-z_]+)'/g)].map((m) => m[1]);
  const parts = partsOf[S.id] || [];
  for (const b of declared)
    if (!registered.includes(b) && !parts.includes(b))
      fail(`${S.href}: 功能栏 ${b} has panels but no controller registers it`);
  for (const b of registered)
    if (!declared.includes(b))
      fail(`assets/scenario-${S.id}.js registers 功能栏 ${b}, which the page has no section for`);

  //: a `needs` naming a bar that does not exist is a run order nobody can
  //: satisfy — and it fails SILENTLY, by never waiting for anything
  for (const m of ctlSrc.matchAll(/needs:\s*\[([^\]]*)\]/g))
    for (const n of [...m[1].matchAll(/'([a-z_]+)'/g)].map((x) => x[1]))
      if (!declared.includes(n))
        fail(`assets/scenario-${S.id}.js: a 功能栏 needs '${n}', which this page does not carry`);
}

// --- 3. every page's `data-page` is a scenario the module knows -----------

for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  const m = src.match(/<body[^>]*data-page="([^"]+)"/);
  if (!m) { fail(`${f} has no data-page`); continue; }
  const id = m[1];
  if (!FLATIDS.includes(id) && !SCENARIOS.some((S) => S.id === id)
      && !TOOLS.some((P) => P.id === id))
    fail(`${f} declares data-page="${id}", which is no page of this site`);
  if (id !== idOf(f)) fail(`${f} declares data-page="${id}" — that is another page`);
  const nav = (src.match(/<nav>([\s\S]*?)<\/nav>/) || ['', ''])[1];
  if (isFlat(f)) {
    //: ★a generated page WRITES its nav, and must not load the runtime that
    //: would inject a second one.  This is the check that keeps the pages
    //: static: the whole point is that they carry no i18n and no `site.js`.
    //: ★comments stripped first: these pages EXPLAIN in their own markup that
    //: their cards came out of the table in `assets/site.js`, and a substring
    //: search over the raw source read that sentence as a script tag.
    const bare = src.replace(/<!--[\s\S]*?-->/g, '');
    for (const forbidden of ['assets/site.js', 'assets/i18n.js', 'assets/lang-'])
      if (bare.includes(forbidden))
        fail(`${f} loads ${forbidden} — a generated page runs no i18n`);
    if (bare.includes('data-i18n'))
      fail(`${f} still carries data-i18n — its text should be in the markup`);
    //: ★the strip is the scenarios AND the tool pages since 2026-09-01 (用户
    //: 裁定; see the note on `TOOLS` in `site.js`).  Order matters and is the
    //: tables' order: the generated nav and the one `installNav` injects into
    //: the dynamic pages have to be the same strip, or a reader crossing from
    //: the entrance into a scenario sees it re-sorted.
    const want = [...SCENARIOS, ...TOOLS].map((S) => S.href);
    const links = [...nav.matchAll(/<a href="([^"]+)"/g)].map((x) => x[1]);
    if (String(links) !== String(want))
      fail(`${f} nav is [${links}], expected [${want}]`);
  } else {
    if (!/assets\/site\.js/.test(src)) fail(`${f} does not load site.js — no navigation`);
    if (/<a\b/.test(nav))
      fail(`${f} still has a hand-written nav link; the nav is injected now`);
  }
}

// --- 4. the element-id prefix, which is what keeps the parts apart -------
//
// Sixty ids collided across the ten former pages (`status`, `run`, `ip`,
// `beta0` …).  A single unprefixed one on a shared page is not a visible
// break: the first part's control answers for the second part's slider.
// ★The toolbar ids are the exception and are NOT checked here: `run`,
// `status`, `progress`, `device` are built by `scenario.js` under the PAGE's
// prefix, because there is one of each per page.

for (const L of SCENARIOS) {
  const src = readFileSync(APP + L.href, 'utf8');
  //: every panel says which part it belongs to, and every id inside it
  //: carries that part's prefix — OR the PAGE's, which is how a parameter
  //: two parts share is spelled: one control, set once for the scenario.
  //: ★the alphabet is [a-z_], not [a-z] — `pulse_design` has an underscore
  //: (FYL-DESIGN-09 D-21).  Two other sites here were widened when the page
  //: was named; THIS one was missed, and the failure is silent: the pattern
  //: simply matches nothing, so all 50 panels of the merged page went
  //: unchecked while the gate kept printing PASS.
  let panels = 0;
  for (const g of src.matchAll(/<[a-z]+ data-part="([a-z_]+)"[\s\S]*?(?=\n\n|<[a-z]+ data-part=)/g)) {
    const [body, part] = [g[0], g[1]];
    panels++;
    for (const m of body.matchAll(/\b(?:id|for)="([^"]+)"/g))
      if (!m[1].startsWith(part + '-') && !m[1].startsWith(L.id + '-'))
        fail(`${L.href}: ${m[1]} in a ${part} panel carries neither prefix`);
  }
  //: ★A pattern that matches NOTHING passes every assertion under it.  That is
  //: how this check went blind on `pulse_design` for a whole page: it is not
  //: enough to widen the alphabet, the gate has to say it found something.
  if (!panels) fail(`${L.href}: no data-part panel matched — the check is vacuous`);
}

// Ids must also be unique across the whole document — the prefix is the
// mechanism, this is the property it exists for.
for (const f of htmls) {
  const seen = new Set();
  for (const m of readFileSync(APP + f, 'utf8').matchAll(/\bid="([^"]+)"/g)) {
    if (seen.has(m[1])) fail(`${f} uses id="${m[1]}" twice`);
    seen.add(m[1]);
  }
}
if (!bad) ok('part panels are prefixed and every id in every page is unique');

// --- 5. message keys, in BOTH languages -----------------------------------
//
// Run every line page's renderer plus the landing page, then add whatever the
// markup asks for statically.

for (const S of SCENARIOS) { main.children.length = 0; globalThis.FySite.render(S.id); }
for (const S of SCENARIOS) {
  wanted.add('ln.' + S.id + '.title');
  wanted.add(S.nav);
  wanted.add(S.card + '.h');
  wanted.add(S.card + '.p');
}
//: ★A TOOL PAGE IS A DESTINATION NOW (2026-09-01) and therefore owns the same
//: two kinds of string a scenario does — a nav label and an entrance card —
//: while owning none of a scenario's `ln.<id>.*` prose, because it renders no
//: lead and no bound.  Both strings are asked for by CODE (`installNav` /
//: `renderHome` on the dynamic side, `make-app-pages.mjs` on the generated
//: one) rather than by a `data-i18n` in any file, so nothing below would find
//: them and the orphan check would report them as prose nobody shows.
for (const P of TOOLS) {
  wanted.add(P.nav);
  wanted.add(P.card + '.h');
  wanted.add(P.card + '.p');
}
wanted.add('nav.home');
for (const f of htmls) {
  const src = readFileSync(APP + f, 'utf8');
  for (const m of src.matchAll(/data-i18n(?:-title)?="([^"]+)"/g)) wanted.add(m[1]);
}
//: ★AND THE TEMPLATES.  The three prose pages are generated, so their keys are
//: no longer named in `app/` at all — they are named in `tools/app-pages/*.html`
//: as `{{key}}`.  Without this the orphan check below would report every
//: `home.*` string as prose nothing shows, on the very day it started showing
//: in two languages instead of one.
const TPL = APP + '../tools/app-pages/';
for (const f of readdirSync(TPL).filter((x) => x.endsWith('.html')))
  for (const m of readFileSync(TPL + f, 'utf8').matchAll(/\{\{([\w.]+)(?:\|text)?\}\}/g))
    wanted.add(m[1]);
//: the footer band is emitted by two different things and named in neither
for (const P of globalThis.FySite.PAGES) wanted.add(P.nav);
wanted.add('foot.copyright');

let missing = 0;
for (const k of [...wanted].sort()) {
  for (const lang of ['zh', 'en'])
    if (!CAT[lang].has(k)) { fail(`message key \`${k}\` is missing from ${lang}`); missing++; }
}
if (!missing) ok(`${wanted.size} message keys, all present in both zh and en`);

// The reverse: a key in one catalogue and not the other is invisible, because
// a missing en key silently falls back to zh.
for (const k of CAT.zh) if (!CAT.en.has(k)) fail(`\`${k}\` is in zh only — en will silently show Chinese`);
for (const k of CAT.en) if (!CAT.zh.has(k)) fail(`\`${k}\` is in en only`);

// Prose keys nobody asks for any more.  Only `home.*` and the line-page
// namespaces are checked: the tool pages build keys by concatenation and
// would produce false positives.
const OWNED = /^(home\.|ln\.|role\.|fr\.|gap\.|why\.|v\.(full|part|todo|no)$|nav\.line\.)/;
const orphans = [...CAT.zh].filter((k) => OWNED.test(k) && !wanted.has(k));
if (orphans.length) fail(`prose no page shows any more: ${orphans.join(', ')}`);
else ok('no orphaned prose in the line and landing catalogues');

console.log(bad ? `\nFAILED (${bad})` : '\nPASS');
process.exit(bad ? 1 : 0);
